<?

define('MSG_upload','Загрузить');
define('MSG_cancel','Отменить');
define('MSG_up','Выше');
define('MSG_down','Ниже');
define('MSG_create','Создать');
define('MSG_nochanges','Без изменений');
define('MSG_nospecial','Нет особого уровня');
define('MSG_add','Добавить');
define('MSG_set','Установить');
define('MSG_forumlevels','Уровни доступа на форум');
define('MSG_alllangs','Все языки');
define('MSG_headers','META-теги форума');
define('MSG_optimized','Оптимизация выполнена');

define('MSG_ct_moved','Категория успешно перемещена');
define('MSG_ct_list','Вернуться к списку категорий');
define('MSG_ct_created','Категория успешно создана');
define('MSG_ct_deleted','Категория успешно удалена');
define('MSG_ct_saved','Параметры категории успешно сохранены');
define('MSG_ct_confirm','Вы действительно хотите удалить эту категорию');

define('MSG_f_forumlist','Список разделов, для которых требуется внести изменения');
define('MSG_f_gparams','Настройка параметров группы разделов');
define('MSG_f_created','Новый форум создан');
define('MSG_f_deleted','Форум успешно удален');
define('MSG_f_saved','Настройки форума успешно сохранены');
define('MSG_f_moved','Форум успешно перемещен');
define('MSG_f_newpic','Значок раздела с новыми сообщениями');
define('MSG_f_nonewpic','Значок раздела без новых сообщений');
define('MSG_f_langs','Языки, для которых будет показываться этот раздел');
define('MSG_f_mainpage','На главной странице');
define('MSG_f_groupdone','Настройки группы форумов сохранены');
define('MSG_f_exchange','Поменять местами');
define('MSG_f_movebefore','Поставить перед');
define('MSG_f_moveafter','Поставить после');
define('MSG_f_move','Для изменения порядка форумов и категорий задайте им сортировочные номера');
define('MSG_f_move2','Сортировка производится по возрастанию, т.е. разделы с большими номерами идут в конец');
define('MSG_f_move3','Сортировочный номер действует только в пределах уровня вложенности раздела, т.е. смена сортировочного номера не приведет к перемещению в другой родит. раздел или категорию');
define('MSG_f_descr_descr','В описании раздела допускается использование BoardCode');
define('MSG_f_confirm','Вы действительно хотите удалить этот раздел');
define('MSG_f_dlurl','URL каталога для загружаемых файлов');
define('MSG_f_dldir','Каталог для загружаемых на сервер файлов');
define('MSG_f_dlurl_descr','Если данное поле пусто, то в данный раздел можно помещать только ссылки');
define('MSG_f_cleared','Очистка потерянных тем и сообщений завершена. Всего удалено');
define('MSG_f_nosubs','Показывать вложенные разделы на главной странице');
define('MSG_f_link','URL данного раздела (только цифры, латинские буквы и _)');
define('MSG_f_link_descr','Если поле будет оставлено пустым, то в качестве URL форума будет использоваться его порядковый номер');
define('MSG_f_dynpage_path','Путь к включаемому в форум скрипту.');
define('MSG_f_dynpage_descr','Путь должен указываться относительно каталога форума. URLы недопустимы из соображений безопасности.');

define('MSG_e_ad_nouser','Пользователя с таким именем не существует');
define('MSG_e_addon_copy','При копировании файла возникла ошибка. Исходный и конечный файлы:');
define('MSG_e_addon_delete','При удалении файла возникла ошибка. Файл:');
define('MSG_e_addon_file','При открытии файла возникла ошибка. Файл:');
define('MSG_e_addon_ibver','Для установки данного дополнения требуется более новая версия Intellect Board');
define('MSG_e_addon_langfile','Не найден файл, который должен быть объединен с существующим языковым файлом');
define('MSG_e_addon_nofile','При загрузке файла произошла ошибка');
define('MSG_e_addon_nolang','Такого языкового файла не существует:');
define('MSG_e_addon_notfound','Требуемый текст не найден в файле. Такое возможно, если файл изменялся вручную или было установлено некорректное дополнение. Замените файл на входящий в дистрибутив и попробуйте еще раз');
define('MSG_e_addon_sqlfile','Не удалось открыть файл с текстом SQL-запросов');
define('MSG_e_addon_versions','Конфликт версий! Уже установленная версия дополнения не может быть заменена данной версией!');
define('MSG_e_av_fileexists','Файл с таким именем уже существует на форуме');
define('MSG_e_av_notuploaded','Файл аватара не был корректно загружен');
define('MSG_e_noforum','Ошибка: нет такого форума!');
define('MSG_e_nouser','Ошибка: нет такого пользователя!');
define('MSG_e_levelexists','Ошибка! Уровень доступа с таким значением уже существует!');
define('MSG_e_invalidlevel','Ошибка! Указан недопустимый уровень пользователя!');
define('MSG_e_badfile','Неправильно указан файл для редактирования!');
define('MSG_e_empty_mail','Текст рассылки не может быть пустым!');
define('MSG_e_g_nogroups','На форуме не существует ни одной группы!');
define('MSG_e_g_notitle','Название группы не может быть пустым');
define('MSG_e_msg_nofile','Не удалось открыть файл с текстами сообщений');
define('MSG_e_nosystem','Профиль пользователя System редактировать нельзя!');
define('MSG_e_notemplate','Не удалось открыть файл шаблона');
define('MSG_e_sm_badfilesize','Файл смайлика имеет слишком большой размер!');
define('MSG_e_sm_badtype','Файл смайлика не является графическим файлом или он поврежден при загрузке!');
define('MSG_e_sm_fileexists','Файл с таким именем уже существует на форуме!');
define('MSG_e_sm_notuploaded','Не удалось загрузить файл смайлика!');
define('MSG_e_st_alreadyexists','Стиль с таким именем уже существует');
define('MSG_e_st_createdir','Не удалось создать каталог для нового стиля. Зайдите на форум по FTP, создайтие каталог вручную, после чего попробуйте еще раз');
define('MSG_e_st_last','Этот стиль является последним, и его удаление приведет к некорректной работе форума');
define('MSG_e_style_badfile','Не удалось октрыть файл набора стилей');
define('MSG_e_u_noparams','Не указан ни один из параметров для очистки пользователей');
define('MSG_e_badsyspass','Неправильно введен пароль пользователя System!');
define('MSG_e_pass_notmatch','Введенные пароли не совпадают');
define('MSG_e_filelist','Для успешной установки дополнения следующие файлы и каталоги должны быть доступны на запись');
define('MSG_e_f_noselected','Нет выбранных разделов');
define('MSG_e_f_noparams','Не задано изменение каких-либо параметров');
define('MSG_e_ctlast','Данная категория является последней. Если вы хотите ее удалить, создайте сначала новую категорию');
define('MSG_e_st_invalidname','Имя файла стиля содержит недопустимые символы');
define('MSG_e_nomailfile','Не найден файл с текстом почтового сообщения');

define('MSG_u_saved','Параметры пользователя успешно сохранены');
define('MSG_u_deleted','Пользователь успешно удален');
define('MSG_u_select','Вернуться к выбору пользователя для редактирования');
define('MSG_u_regged','зарегистрировался');

define('MSG_l_delete','Уровень успешно удален');
define('MSG_l_saved','Уровень успешно сохранен');
define('MSG_l_created','Уровень успешно создан');
define('MSG_l_noname','(безымянный уровень)');

define('MSG_cat_forum','Разделы');
define('MSG_ad_forum','Настройка разделов и категорий');
define('MSG_ad_fgroup','Операции над несколькими разделами');
define('MSG_ad_blog_gal_settings','Настройки блогов и галерей');
define('MSG_cat_user','Пользователи');
define('MSG_ad_userlist','Список пользователей');
define('MSG_ad_user','Редактирование пользователя');
define('MSG_ad_createuser','Создать пользователя');
define('MSG_ad_deluser','Удалить пользователя');
define('MSG_ad_level','Уровни доступа');
define('MSG_ad_groups','Группы участников');
define('MSG_ad_grouplevel','Уровни доступа групп');
define('MSG_ad_clearusers','Удаление малоактивных пользователей');
define('MSG_ad_bannedusers','Изгнанные участники');
define('MSG_ad_inactiveusers','Неактивные участники');
define('MSG_ad_warnings','Предупреждения/поощрения');
define('MSG_cat_settings','Настройки');
define('MSG_ad_basic','Основные параметры');
define('MSG_ad_graphics','Настройки фотографий и файлов');
define('MSG_ad_modes','Настройки режимов работы');
define('MSG_ad_rules','Правила форума');
define('MSG_ad_badwords','Запрещенные слова');
define('MSG_ad_banip','Запрет доступа по IP');
define('MSG_cat_actions','Действия');
define('MSG_ad_fileconvert','Перенос файлов');
define('MSG_ad_photoconvert','Перенос фото');
define('MSG_ad_mailsend','Администраторская рассылка');
define('MSG_ad_addon','Установка дополнений');
define('MSG_ad_upload','Загрузка смайликов и аватаров');
define('MSG_ad_sql','Выполнить SQL-запрос');
define('MSG_ad_backup','Резервное копирование');
define('MSG_ad_backup_files','Файлы резервных копий');
define('MSG_ad_resync','Пересчет статистики');
define('MSG_ad_optimize','Оптимизировать базу данных');
define('MSG_ad_syspass','Смена пароля пользователя System');
define('MSG_ad_losttopic','Очистка от потерянных тем');
define('MSG_cat_interface','Интерфейс');
define('MSG_ad_styles','Редактор стилей');
define('MSG_ad_msg','Редактор сообщений');
define('MSG_ad_tmplmain','Основной шаблон');
define('MSG_ad_tmplq','Шаблон промежуточных сообщений');
define('MSG_ad_headers','Заголовки форума');
define('MSG_ad_topcounter','Заголовок форума');
define('MSG_ad_bottomcounter','Нижняя часть форума');
define('MSG_ad_tmplmail','Почтовые шаблоны');
define('MSG_cat_stats','Статистика');
define('MSG_ad_statcommon','Общая статистика');
define('MSG_ad_stataction','Статистика по действиям');
define('MSG_ad_statbrowser','Статистика по броузерам');
define('MSG_ad_statactivity','Стастистика по популярности');
define('MSG_ad_statdetail','Детализированная статистика');
define('MSG_cat_quit','Выход');
define('MSG_ad_quit','Вернуться на форум');
define('MSG_ad_quitguest','Вернуться на форум как гость');
define('MSG_cat_support','Поддержка Intellect Board');
define('MSG_ad_site','Официальный сайт');
define('MSG_ad_suppforum','Форум поддержки');
define('MSG_ad_boardcodes','Коды BoardCode');
define('MSG_ad_canonize','"Канонизация" пользователей');
define('MSG_ad_mail_generation','Генерация списка обновлений');
define('MSG_ad_mail_period','Сгенерировать список обновлений за последние');
define('MSG_ad_mail_days','дней');
define('MSG_ad_mail_generate','Сгенерировать');
define('MSG_ad_mail_forums','Разделы');

define('MSG_tp_standart','Стандартный раздел');
define('MSG_tp_container','Контейнер (раздел для вложенных разделов)');
define('MSG_tp_irc','IRC-чат');
define('MSG_tp_extlink','Внешняя ссылка');
define('MSG_tp_article','Статьи');
define('MSG_tp_download','Файлы для скачивания');
define('MSG_tp_news','Новости');
define('MSG_tp_presentation','Статическая страница (может содержать подразделы)');
define('MSG_tp_encyclopedia','Энциклопедия');
define('MSG_tp_photos','Фотогалерея');
define('MSG_tp_blog','Блог пользователя');
define('MSG_tp_gallery','Галерея пользователя');
define('MSG_tp_dynpage','Динамическая страница');

define('MSG_addons','Установленные на форуме дополнения (add-ons)');
define('MSG_addon_name','Название');
define('MSG_addon_ver','Версия');
define('MSG_addon_decr','Описание');
define('MSG_addon_upload','Загрузка файла, содержащего дополнения');
define('MSG_addon_upload_descr','Если у вас не подключен PHP-модуль ZZIPlib, файл обновления не может быть разархивирован на сервере. В этом случае разархивируйте файл дополнений на своем компьютере и загрузите содержимое архива в подкаталог temp по FTP.');
define('MSG_addon_install','Установить загруженное обновление');
define('MSG_addon_path','Укажите путь к файлу обновлений на вашем компьютере');
define('MSG_addon_doinstall','Установка дополнения');

define('MSG_opt_params','Основные параметры форума');
define('MSG_opt_title','Название форума');
define('MSG_opt_descr','Описание форума');
define('MSG_opt_copyright','Сообщение об авторских правах');
define('MSG_opt_copydescr','<br>Символ &copy; добавляется в начало автоматически');
define('MSG_opt_path','Путь к скриптам форума на сервере');
define('MSG_opt_url','URL форума');
define('MSG_opt_email','Адрес исходящих писем');
define('MSG_opt_misc','Дополнительные настройки форума');
define('MSG_opt_cyr','Использование символов кириллицы в именах пользователей');
define('MSG_opt_here','Время присутствия пользователя на форуме');
define('MSG_opt_visittime','Время неактивности для начала нового визита');
define('MSG_opt_logs','Ведение логов форума');
define('MSG_opt_logs_descr','Примечание: отключение логов приведет к тому, что количество присутствющих на форуме пользователей будет отображаться неправильно');
define('MSG_opt_hereminutes','минут');
define('MSG_opt_logall','Включено для всех');
define('MSG_opt_logreg','Включено для зарегистрированных');
define('MSG_opt_lognone','Выключено');
define('MSG_opt_gzip','Использование GZIP-сжатия для страниц форума');
define('MSG_opt_encrypt','Шифрование паролей форума');
define('MSG_opt_cryptoff','Выключено');
define('MSG_opt_crypton','Включено');
define('MSG_opt_cryptuser','Определяется пользователеми');
define('MSG_opt_flood','Защита от флуда');
define('MSG_opt_floodsec','секунд');
define('MSG_opt_activate','Активация пользователя при регистрации');
define('MSG_opt_actnone','Не требуется');
define('MSG_opt_actemail','Через E-mail');
define('MSG_opt_admin','Выполняется только администратором');
define('MSG_opt_reginfo','Рассылка уведомлений о регистрации новых пользователей');
define('MSG_opt_regon','Выключена');
define('MSG_opt_regoff','Включена');
define('MSG_opt_posttitle','Заголовки сообщений');
define('MSG_opt_pton','Включены');
define('MSG_opt_ptoff','Выключены');
define('MSG_opt_defvotecount','Количество вариантов голосования по умолчанию');
define('MSG_opt_fixviews','Фиксация просмотров тем');
define('MSG_opt_fixviews_descr','Внимание! Включение данной опции может привести к существенному увеличению размера форума');
define('MSG_opt_fixon','Включена');
define('MSG_opt_fixoff','Выключена');
define('MSG_opt_warnstoban','Количество предупреждений, после которых пользователь получает статус "Изгнанный"');
define('MSG_opt_ratetime','Количество дней, после которых возможно повторное изменение рейтинга пользователя');
define('MSG_opt_ltitle','Уровень для самостоятельного редактирования звания участника');
define('MSG_opt_avatars','Настройки аватаров и фотографий');
define('MSG_opt_maxavatarsize','Максимальный размер загруженного аватара');
define('MSG_opt_maxavsize_descr','0 - отключить возможность загрузки');
define('MSG_opt_bytes','байт');
define('MSG_opt_maxphoto','Максимальный размер загруженной фотографии в профиле');
define('MSG_opt_maxavatarx','Максимальная ширина загруженного аватара');
define('MSG_opt_pixels','пикселей');
define('MSG_opt_maxavatary','Максимальная высота загруженного аватара');
define('MSG_opt_avatarx','Отображаемая ширина аватаров');
define('MSG_opt_avatary','Максимальная высота аватаров');
define('MSG_opt_avatarx_descr','Оставьте это поле пустым, чтобы аватары отображались без масштабирования');
define('MSG_opt_avatary_descr','Оставьте это поле пустым, чтобы аватары отображались без масштабирования');
define('MSG_opt_attach_settings','Настройки прикрепленных файлов');
define('MSG_opt_maxfileattach','Максимальный размер прикрепленного файла');
define('MSG_opt_previewx','Максимальная ширина прикрепленной картинки при предпросмотре');
define('MSG_opt_previewy','Максимальная высота прикрепленной картинки при предпросмотре');
define('MSG_opt_closetext','Текст, выводимый при закрытии форума');
define('MSG_opt_showpresent','Где показывать список присутствующих пользователей');
define('MSG_opt_status','Закрыть форум?');
define('MSG_opt_keeplogs','Количество дней, в течение которых следует хранить записи лога');
define('MSG_opt_secbrowser','Защита от подмены броузера');
define('MSG_opt_secbrowser_descr','Эта защита запрещает подмену броузера (проверка переменной USER_AGENT) при использовании функции "Запомнить пользователя", что может затруднить использование XSS-уязвимостей (но не защитит от них полностью).');
define('MSG_opt_ddos','Защита от DDoS-атак');
define('MSG_opt_ddos_descr','Данная мера безопасности позволяет защититься от автоматических регистраций путем показа картинки со случайным числом, которое пользователь затем должен ввести. Однако это может сделать невозможной регистрацию для пользователей текстовых броузеров (в частности, Lynx и Links)');
define('MSG_opt_ddos_reg','При регистрации и отправке почтового уведомления');
define('MSG_opt_ddos_all','При регистрации, отправке почтового уведомления, а также при отправке сообщения на форум гостями');
define('MSG_opt_security','Меры безопасности');
define('MSG_opt_directlink','Использовать прямые ссылки');
define('MSG_opt_direct_descr','Для того, чтобы подсчитать количество скачиваний программы, прямые ссылки должны быть выключены, однако это может вызвать проблемы с некоторыми Download-managers');
define('MSG_opt_news','Опции новостей');
define('MSG_opt_news_mainmode','Режим отображения новостей на главной странице');
define('MSG_opt_news_days','Отображать новости за указанное количество дней');
define('MSG_opt_news_count','Отображать указанное количество новостей');
define('MSG_opt_news_both','Отображать не более указанного количества новостей за указанное количество дней');
define('MSG_opt_news_maindays','Количество дней для отображения новостей на главной странице');
define('MSG_opt_news_maincount','Количество новостей для отображения на главной странице');
define('MSG_opt_f_mode','Режим отображения новостей в разделе');
define('MSG_opt_f_maindays','Количество дней для отображения новостей в разделе');
define('MSG_opt_f_maincount','Количество новостей для отображения в разделе');
define('MSG_opt_GD2','Использовать графическую библиотеку GD2');
define('MSG_opt_GD2descr','Использование GD2 позволяет улучшить качество уменьшенных рисунков, однако библиотека GD2 доступна не на всех хостингах');
define('MSG_opt_submenu','Показывать вложенные разделы в меню');
define('MSG_opt_noname_mail','Использовать адреса вида адрес@хост вместо Имя <адрес@хост>');
define('MSG_opt_noname_mail_descr','Если ваш почтовый сервер сообщает об ошибке Invalid address при попытке отправить письмо, попробуйте включить эту опцию');
define('MSG_opt_logo','URL логотипа форума');
define('MSG_opt_logo_instead','Показывать логотип вместо названия форума');
define('MSG_opt_logo_instead_descr','Если вы выберите "Да", будет показываться только логотип, если вы выберите нет, рядом с логотипом будет также писаться и название форума');
define('MSG_opt_rating','Рейтинг пользователей включен');
define('MSG_opt_rating_descr','Если рейтинг включен, то пользователи могут голосовать "за" или "против" других пользователей');
define('MSG_opt_reputaion','Репутация пользователей показывается всем');
define('MSG_opt_reputation_descr','Если выбрать вариант "нет", то репутация будет показываться только администраторам и модераторам');
define('MSG_opt_mainpage','В качесте главной страницы показывать');
define('MSG_opt_forumlist','Список разделов');
define('MSG_opt_minpost','Минимальный размер сообщения');
define('MSG_opt_maxpost','Максимальный размер сообщения');
define('MSG_opt_sigpics','Использование картинок (тег [img]) в подписях');
define('MSG_opt_galery','Настройки фотогалереи');
define('MSG_opt_photos_line','Количество фотографий в строке при предварительном просмотре');
define('MSG_opt_photo_thumb_y','Высота уменьшенной картинки при предварительном просмотре');
define('MSG_opt_photo_size_x_descr','Внимание: изменения этого и следующих параметров не затронут уже существующие фотографии');
define('MSG_opt_photo_size_x','Ширина полной фотографии при ее просмотре');
define('MSG_opt_thumb_qlty','Качество картинок для предварительного просмотра');
define('MSG_opt_thumb_qlty_descr','Допустимы значения от 0 до 100');
define('MSG_opt_photo_qlty','Качество полных фотографий');
define('MSG_opt_photo_order','Порядок сортировки фотографий');
define('MSG_opt_photo_inverse','В обратном порядке (новые -- в начале страницы)');
define('MSG_opt_photo_linear','В хронологическом порядке');
define('MSG_opt_photo_maxsize','Максимальный размер фотографии в альбоме');
define('MSG_opt_impersonation','Имперсонализация');
define('MSG_opt_impersonation_descr','Если эта возможность включена, пользователь, имеющий в разделе права Администратора (1000 и выше) может отправлять туда сообщения от имени любого пользователя');
define('MSG_opt_article_split','Количество символов при разбиении статьи на страницы');
define('MSG_opt_article_split_descr','Примечание: количество символов - приблизительное, на самом деле оно округляется в большую сторону до ближайшей границы абзаца');
define('MSG_opt_mustfields','Обязательные для заполнения поля');
define('MSG_opt_mustmsg','Сообщение, выводимое при незаполненных полях');
define('MSG_opt_brutetimeout','Таймаут для защиты от подбора пароля');
define('MSG_opt_summary','Выводить суммарную статистику форума');
define('MSG_opt_foreword','Вступительное слово');
define('MSG_opt_foreworddescr','Здесь можно разместить краткое описание вашего сайта. Оно будет выводиться над списком разделов на титульной странице');
define('MSG_opt_exttopic','Расширенные настройки показа тем в разделах включены');
define('MSG_opt_ratinglevel','Уровень, при котором возможно влияние на рейтинг других пользователей');
define('MSG_opt_noquickreg','Быстрая регистрация возможна');
define('MSG_opt_top','Над списком разделов');
define('MSG_opt_bottom','Под списком разделов');
define('MSG_opt_nooutput','Не выводить');
define('MSG_opt_fwelcome','Приветствие внутри раздела');
define('MSG_opt_ftop','Над списком тем');
define('MSG_opt_fbottom','Под списком тем');
define('MSG_opt_maxphotox','Максимальная ширина личной фотографии');
define('MSG_opt_maxphotoy','Максимальная высота личной фотографии');
define('MSG_opt_nowhere','Не показывать');
define('MSG_opt_titlepage','Показывать только на главной странице');
define('MSG_opt_forums','Показывать на главной странице и в разделах');
define('MSG_opt_topics','Показывать на главной странице, в разделах и темах');
define('MSG_opt_timeregion','Часовой пояс времени на сервере');
define('MSG_opt_announce','Объявление на форуме');
define('MSG_opt_annone','Выключено');
define('MSG_opt_antitle','Только на главной странице');
define('MSG_opt_anall','На всех страницах форума');
define('MSG_opt_announcetext','Текст объявления');
define('MSG_opt_andescr','В тексте объявления можно использовать HTML, BCode, смайлики');
define('MSG_opt_hot','Количество сообщений, после которых тема считается "горячей"');
define('MSG_opt_imgtag','Режим работы тега IMG');
define('MSG_opt_imgpics','вставка картинок');
define('MSG_opt_imgicons','вставка значков-ссылок');
define('MSG_opt_imglimit_x','Ограничение размера картинки по ширине');
define('MSG_opt_imglimit_y','Ограничение размера картинки по высоте');
define('MSG_opt_search_limit','Максимальное количество результатов одного поискового запроса');
define('MSG_opt_search_count','Максимальное количество сохраненных поисковых запросов');
define('MSG_opt_user','Настройки отображения пользователей');
define('MSG_opt_search','Настройки поиска');
define('MSG_opt_tagimg','Настройки свойств тега IMG');
define('MSG_opt_nomailsend','Почтовые функции форума');
define('MSG_opt_search_ext','Расширенный поиск по форуму');
define('MSG_opt_search_ext_descr','Расширенный поиск позовляет использовать операторы + - * ~ в поисковом запросе. Для его использования необходим MySQL 4.0 и выше');
define('MSG_opt_search_impl','Поиск с использованием неявного знания');
define('MSG_opt_search_impl_descr','Позволяет улучшить результаты поиска, однако это увеличивает нагрузку на БД почти в 2 раза. Для использования необходим MySQL 4.0 и выше');
define('MSG_opt_topiccount','Показ числа созданных пользователем тем');
define('MSG_opt_topiccount_descr','Включение данной опции может привести к резкому увеличению нагрузки на БД в момент индексации профилей пользователей поисковым роботом');
define('MSG_opt_noutput','Не выводить');
define('MSG_opt_hinttext','Длина текста подсказки в списке тем (0 &mdash; выключить)');
define('MSG_opt_location_bottom','Вывод указателя местанахождения на форуме перед формой ответа');
define('MSG_opt_updated_time','Время, за которое по умолчанию показывать сообщения в списке обновившихся');
define('MSG_opt_hurl','Использовать человекочитаемые URL (HURLs)');
define('MSG_opt_hurl_descr','Для корректной работы HURL необходимо раскомментировать соответствующие строки в файле .htaccess');
define('MSG_opt_nameletters','Допустимые символы в именах пользователей');
define('MSG_opt_nameletters_descr','Обработка производится с помощью выражения preg_match([указанные_символы])');
define('MSG_opt_complain','Функция жалобы модератору');
define('MSG_opt_complain_all','Разрешено всем');
define('MSG_opt_complain_noguest','Разрешено только зарегистрированным');
define('MSG_opt_complain_nobody','Запрещено');
define('MSG_opt_blogparams','Параметры блогов');
define('MSG_opt_blog_level','Уровень для создания блога');
define('MSG_opt_blog_cat','Категория, к которой приписаны блоги');
define('MSG_opt_blog_container','Контейнер для размещения блогов');
define('MSG_opt_galleryparams','Параметры пользовательских галерей');
define('MSG_opt_gallery_level','Уровень для создания галереи');
define('MSG_opt_gallery_cat','Категория, к которой приписаны галереи');
define('MSG_opt_gallery_container','Контейнер для размещения галерей');
define('MSG_opt_notshow','Не отображать в списке разделов');
define('MSG_opt_hurlindex','Через index.php/путь');
define('MSG_opt_sendmail_days','Количество дней по умолчанию для рассылки уведомлений');
define('MSG_opt_norateperiod','Количетво дней с отправки последнего сообщения, после которого пользователь лишается возможности влиять на рейтинг');

define('MSG_bw_list','Список запрещененных слов');
define('MSG_bw_word','Слово');
define('MSG_bw_replace','Заменять на');
define('MSG_bw_add','Добавить новые запрещенные слова');
define('MSG_bw_onlyname','Только в именах пользователей');

define('MSG_lang_selection','Выбор языка');
define('MSG_lang_select','Выберите язык');

define('MSG_rules_edit','Редактирование правил форума');

define('MSG_template_descr','Шаблон представляет собой обычный PHP-файл, в котором могут быть использованы следующие обозначения:');
define('MSG_template_comment1','main_header(); - основной заголовок форума');
define('MSG_template_comment2','main_menu(); - главное меню');
define('MSG_template_comment3','main_location($locations); - указатель на текущее местоположение на форуме');
define('MSG_template_comment4','main_start(); - начало основной части форума');
define('MSG_template_comment5','main_action(); - вызов функции, реализующей основное действие');
define('MSG_template_comment6','time_diff(); - определение времени выполнения скрипта');
define('MSG_template_comment7','main_end(); - конец основной части форума');
define('MSG_template_comment8','menu(); - список разделов форума в виде меню');
define('MSG_template_comment9','main_copyright(); - вывод copyright-сообщения');
define('MSG_template_comment10','announce(); - объявление форума');
define('MSG_template_comment11','last_topics(количество, тип); -- вывод списка последних тем (если количество не указано явно, оно считается равным 10), тип -- определяет тип раздела. 0 -- вывод из разделов любого типа, 1 -- только из стандарных форумов.');
define('MSG_template_comment12','active_topics(количество, тип, период); -- вывод списка наиболее активных тем (т.е. тех, в которых было больше всего сообщений и последнее обновление приходится за указанный в днях период), параметры количество и тип -- аналогичны параметрам last_topics');
define('MSG_template_comment13','small_search_form(); - малая поисковая форма (по всему форуму сразу без выбора подраздела)');
define('MSG_template_comment14','big_search_form(); - большая поисковая форма (с возможностью выбора разделов и сортировки)');
define('MSG_template_comment15','action_start(); - начало вывода результатов основного действия');
define('MSG_template_comment16','action_end(); - конец вывода результатов основного действия');
define('MSG_template_comment17','present_list(); - список присутствующих на форуме/в разделе/в теме');
define('MSG_template_comment18','fast_switch(); - быстрое переключение между форумами с помощью Select');
define('MSG_template_comment19','show_vote(номер_темы); - отображения голосования из какой-либо темы в заданном месте');
define('MSG_template_comment20','user_rating(количество,поле_сортировки,заголовок,без_администраторов); - показ в заданном месте рейтинга пользователей с сортировкой по заданному признаку');
define('MSG_template_comment21','allowed_actions() -- cписок доступных пользователю действий');
define('MSG_template_comment22','show_news_feed(раздел,заголовок,количество,период) -- вывод ленты новостей из указанного раздела в произвольной форме. ');

define('MSG_template_mail','Выбор почтового шаблона для редактирования');
define('MSG_template_select','Выберите почтовый шаблон');
define('MSG_template_edit','Редактирование почтового шаблона');

define('MSG_ad_mailsend','Администраторская рассылка');
define('MSG_ad_mailtext','Текст сообщения');
define('MSG_ad_mailtext_descr','Используйте $username в качестве имени пользователя');

define('MSG_avatar_upload','Загрузка аватара');
define('MSG_avatar_local','Локальный путь');
define('MSG_avatar_uploaded','Всего аватаров загружено');

define('MSG_smile_upload','Загрузка смайлика');
define('MSG_smile_code','Обозначение смайлика');
define('MSG_smile_local','Локальный путь');
define('MSG_smile_list','Список уже загруженных смайликов');
define('MSG_smile_pic','Картинка смайлика');
define('MSG_smile_show','Показывать смайлик на форме отправки сообщения');
define('MSG_smile_uploaded','Всего смайликов загружено');
define('MSG_smile_deleted','Смайлик удален');
define('MSG_smile_edit_code','Редактирование кода');
define('MSG_smile_edit_file','Замена файла');

define('MSG_sql','Выполнение SQL-запроса');
define('MSG_sql_text','Текст запроса');
define('MSG_sql_exec','Выполнить');
define('MSG_sql_results','Результаты выполнения SQL-запроса');

define('MSG_ct_list','Список разделов и категорий форума');
define('MSG_ct_newf','Новый раздел');
define('MSG_ct_create','Создание новой категории');
define('MSG_ct_newtitle','Название новой категории');
define('MSG_ct_edit','Редактирование категории');
define('MSG_ct_title','Название категории');
define('MSG_ct_createf','Создание нового раздела');
define('MSG_ct_newtype','Тип нового раздела');

define('MSG_g_list','Список имеющихся на форуме групп пользователей');
define('MSG_g_title','Название группы');
define('MSG_g_count','Количество пользователей');
define('MSG_g_actions','Действия');
define('MSG_g_goto','Перейти к группе');
define('MSG_g_setlevel','Установить уровни');
define('MSG_g_create','Создать новую группу');
define('MSG_g_params','Параметры группы пользователей');
define('MSG_g_title','Название группы');
define('MSG_g_descr','Описание группы');
define('MSG_g_lview','Уровень, при котором группа становится видимой');
define('MSG_g_ljoin','Уровень для подачи заявки на вступление');
define('MSG_g_lautojoin','Уровень для автоматического вступления');
define('MSG_g_allowquit','Разрешать пользователям самостоятельно выходить из группы');
define('MSG_g_coords','Координаторы группы');
define('MSG_g_setlevel','Вы можете установить уровени доступа, которые устанавливаются при вступлении в группу, в разделе "Уровень доступа группы"');
define('MSG_g_addcoords','Добавить координаторов');
define('MSG_g_levels','Уровни доступа для группы');
define('MSG_g_group','Группа');
define('MSG_g_mainlevel','Основной уровень доступа');
define('MSG_g_applyto','Применить к');
define('MSG_g_newusers','пользователям, вступающим в группу');
define('MSG_g_users','пользователям, уже находящимся в группах');
define('MSG_g_both','и к тем, и к другим');
define('MSG_g_setlevelset','Уровни доступа выставлены');

define('MSG_msg_toedit','Сообщения для редактирования');
define('MSG_msg_user','пользовательские');
define('MSG_msg_admin','администраторские');
define('MSG_msg_edit','Редактирование сообщений');
define('MSG_msg_add','Добавление нового сообщения');
define('MSG_msg_code','Обозначение сообщения');
define('MSG_msg_descr','(должно начинаться с MSG_, иначе MSG_ будет добавлено автоматически)');
define('MSG_msg_text','Текст сообщения');

define('MSG_stats_forum','Статистика форума');
define('MSG_stats_common','Общая информация');
define('MSG_stats_title','Название форума');
define('MSG_stats_url','URL форума');
define('MSG_stats_dir','Каталог форума');
define('MSG_stats_server','Сервер');
define('MSG_stats_date','Текущая дата и время');
define('MSG_stats_qualities','Количественные показатели');
define('MSG_stats_posts','Количество сообщений');
define('MSG_stats_topics','Количество тем');
define('MSG_stats_users','Количество пользователей');
define('MSG_stats_misc','Прочая информация');
define('MSG_stats_ppert','Среднее количество сообщений в теме');
define('MSG_stats_pperu','Среднее количество сообщений на пользователя');
define('MSG_stats_tperu','Среднее количество тем на пользователя');
define('MSG_stats_lastpost','Последнее сообщение');
define('MSG_stats_lastuser','Последний зарегистрировавшийся пользователь');
define('MSG_stats_stats','Статистика форума');
define('MSG_stats_showfrom','Показать статистику с');
define('MSG_stats_till','До');
define('MSG_stats_show','Вывести');
define('MSG_stats_hits','Количество просмотров страниц (хиты)');
define('MSG_stats_truehits','Количество просмотров основных страниц');
define('MSG_stats_sessions','Количество сессий пользователей');
define('MSG_stats_hosts','Количество уникальных IP-адресов (хосты)');
define('MSG_stats_users','Количество уникальных зарегистрированных пользователей');
define('MSG_stats_searches','Количество поисковых запросов');
define('MSG_stats_mainpages','Количество просмотров главной страницы');
define('MSG_stats_forumviews','Количество просмотров разделов');
define('MSG_stats_topicviews','Количество просмотров тем');
define('MSG_stats_hperu','Среднее количество хитов на пользователя');
define('MSG_stats_hpers','Среднее количество хитов за сессию');
define('MSG_stats_speru','Среднее количество сессий на пользователя');
define('MSG_stats_group','Группировать результаты');
define('MSG_stats_alltime','за весь период');
define('MSG_stats_byday','по дням');
define('MSG_stats_byweek','по дням недели');
define('MSG_stats_byhour','по часам');
define('MSG_stats_from','Статистика форума с');
define('MSG_stats_till2','по');
define('MSG_stats_perpage','Количество тем на страницу');
define('MSG_stat_period','Период');
define('MSG_stat_hits','Хиты');
define('MSG_stat_truehits','Основные хиты');
define('MSG_stat_sessions','Сессии');
define('MSG_stat_hosts','Хосты');
define('MSG_stat_users','Пользователи');
define('MSG_stat_topics','Темы');
define('MSG_stat_posts','Сообщения');
define('MSG_stat_searches','Поиск');
define('MSG_stat_mainpage','Просмотры главной страницы');
define('MSG_stat_forumviews','Просмотры разделов');
define('MSG_stat_topicviews','Просмотры тем');
define('MSG_stat_hpers','Хитов на сессию');
define('MSG_stat_hperu','Хитов на пользователя');
define('MSG_stat_speru','Сессий на пользователя');
define('MSG_stat_hperu','Хитов на пользователя');
define('MSG_stats_perbrowser','Статистика используемых пользователями броузеров');
define('MSG_stats_browser','Броузер');
define('MSG_stats_percent','Процентная доля по числу пользователей');
define('MSG_stats_percent_active','Процентная доля по активности');
define('MSG_stats_views','Статистика форума по просмотрам');
define('MSG_stats_external','Просмотры форума по переходам с внешних ссылок');
define('MSG_stats_forum','Просмотры списков тем разделов');
define('MSG_stats_forumtopic','Просмотры разделов, включая входящие в них темы');
define('MSG_stats_topic','Просмотры тем');
define('MSG_stats_detailed','Детализированная статистика форума');
define('MSG_stats_detailedfrom','Детальная статистика форума с');
define('MSG_stats_premod','Сообщений, находящихся на премодерации');
define('MSG_stats_syncdone','Пересчет статистики выполнен');
define('MSG_stats_user','Скрипт выполняется от имени пользователя');
define('MSG_stats_dbsize','Размер базы данных');
define('MSG_stats_attachments','Файлов в приложениях');
define('MSG_stats_dayly','Сообщений за последние сутки');
define('MSG_stats_weekly','Сообщений за неделю');
define('MSG_stats_search','Индексация поисковыми системами');
define('MSG_stats_admins','Администраторы форума');
define('MSG_stats_filter','Фильтр статистики (незаполненные поля на выборку не влияют)');
define('MSG_stats_username','Только пользователи (указать имена, разделенные запятыми)');
define('MSG_stats_usermode','Режим проверки имени');
define('MSG_stats_fullmatch','Точное совпадение');
define('MSG_stats_starts','Начинается с');
define('MSG_stats_contains','Содержит');
define('MSG_stats_forumnums','Только действия в разделах (указать номера через запятую)');
define('MSG_stats_topicnums','Только действия в темах (указать номера через запятую)');
define('MSG_stats_ips','Только действия с IP-адресов');

define('MSG_st_selection','Выбор набора стилей для редактирования');
define('MSG_st_select','Выберите стиль');
define('MSG_st_selfordelete','Выбор набора стилей для удаления');
define('MSG_st_create','Создание нового набора стилей');
define('MSG_st_base','Выберите стиль, который будет использоваться в качестве основы');
define('MSG_st_newname','Введите название нового стиля');
define('MSG_st_newfile','Введите имя каталога нового стиля');
define('MSG_st_list','Список стилей в наборе');
define('MSG_st_return','Вернуться к списку стилей');
define('MSG_st_replacecolor','Глобальная замена цвета во всех стилях набора');
define('MSG_st_replacefrom','Введите цвет, который нужно заменить');
define('MSG_st_replaceto','Введите цвет, на который нужно заменить');
define('MSG_st_edit','Редактирования стиля');
define('MSG_st_fromset','из набора');
define('MSG_st_miscparams','Дополнительные параметры');
define('MSG_st_changed','Режим показа стиля изменен');
define('MSG_st_created','Новый стиль успешно создан');
define('MSG_st_replaced','Замена цвета выполнена');
define('MSG_st_return_list','Вернуться к списку стилей');
define('MSG_st_confirm','Вы действительно хотите удалить стиль');
define('MSG_st_confirm_set','Вы действительно хотите удалить набор стилей');
define('MSG_st_created','Новый стиль успешно создан');
define('MSG_st_delete','Удалить стиль');
define('MSG_st_deleted','Стиль удален');
define('MSG_st_saved','Стиль успешно сохранен');
define('MSG_st_docreate','Создать стиль');
define('MSG_st_name','Название набора стилей');
define('MSG_st_status','Режим показа стиля');
define('MSG_st_parent','Родительский стиль');
define('MSG_st_visible','Видимый');
define('MSG_st_hidden','Скрытый');
define('MSG_st_css_saved','CSS-файл успешно сохранен');
define('MSG_st_cssedit','Редактирование CSS-файла');
define('MSG_st_change','Сменить стиль');
define('MSG_st_change_style','Принудительная смена стиля для всех пользователей');
define('MSG_st_changed','Принудительная смена стиля выполнена');
define('MSG_st_edit_template','Редактирование шаблона стиля');
define('MSG_st_template','Редактировать шаблон');
define('MSG_st_dontdelete','Пожалуйста, не удаляйте ссылки на www.openproj.ru и intboard.ru из шаблонов! Умейте уважать чужой труд!');

define('MSG_u_edit','Редактирование профиля пользователя');
define('MSG_u_inputname','Введите имя пользователя, профиль которого вы хотите отредактировать');
define('MSG_u_editguest','Введите имя пользователя, профиль которого вы хотите отредактировать');
define('MSG_u_editnewuser','Чтобы отредактировать параметры профиля, предлагаемые новым участникам, введите NewUser');
define('MSG_u_levels','Установка уровней доступа');
define('MSG_u_guestnew','Здесь также можно использовать Guest и NewUser');
define('MSG_u_nochange','Без изменений');
define('MSG_u_forumlevels','Уровень доступа к разделам');
define('MSG_u_nospecial','Нет особого уровня');
define('MSG_u_email','E-mail');
define('MSG_u_clearlist','Следующие пользователи будут удалены');
define('MSG_u_cleared','Пользователи были удалены');

define('MSG_title_name','Название уровня');
define('MSG_title_level','Уровень доступа');
define('MSG_title_posts','Количество сообщений');
define('MSG_title_actions','Действия');
define('MSG_title_unique','уникальный');
define('MSG_title_levelvalue','Числовое значение уровня доступа (от 1 до 1023)');
define('MSG_title_isunique','Уровень является специальным');
define('MSG_title_minposts','Количество сообщений, необоходимое для получения данного уровня');
define('MSG_title_minposts_descr','(только для тех уровней, которые не являются специальными)');
define('MSG_title_pic','Картинка для уровня (не обязательна)');

define('MSG_u_list','Список участников форума');
define('MSG_u_letter','Выберите букву');
define('MSG_u_letterlist','Список пользователей с именами на букву');

define('MSG_addon_descr','Описание дополнения');
define('MSG_addon_go','Перейти к списку установленных дополнений');
define('MSG_addon_installed','Дополнение успешно установлено');

define('MSG_admin_mail','Рассылка форума');

define('MSG_bottom_counters','Нижние счетчики');

define('MSG_bw_go','Вернуться к списку запрещенных слов');
define('MSG_bw_updated','Список запрещенных слов успешно изменен');

define('MSG_forum','Раздел');

define('MSG_g_changed','Список координаторов группы успешно изменен');
define('MSG_g_created','Группа успешно создана');
define('MSG_g_delete','Группа удалена');
define('MSG_g_levelset','Уровни доступа успешно выставлены');
define('MSG_g_saved','Параметры группы успешно сохранены');

define('MSG_go_stats','Перейти к статистике форума');

define('MSG_l_create','Создание нового уровня доступа');
define('MSG_l_edit','Редактирование уровня доступа');
define('MSG_l_select','Перейти к списку уровней доступа');

define('MSG_mail_foredit','для редактирования почтового шаблона');
define('MSG_mail_go','Перейти к списку почтовых шаблонов');
define('MSG_mail_saved','Почтовый шаблон успешно сохранен');
define('MSG_mail_send','Рассылка завершена. Отправлено писем');
define('MSG_mail_error','ошибок при отправке письма');
define('MSG_mail_errors','Список адресов, на которых возникли ошибки, можно посмотреть в ');
define('MSG_mail_partsend','Очередная часть сообщений отправлена');
define('MSG_mail_click','Нажмите на эту ссылку для продолжения отправки, если в вашем броузер не разрешен автоматический переход');
define('MSG_mail_send_go','Вернуться к отправке сообщения');

define('MSG_main_template','Основной шаблон форума');

define('MSG_msg_list','Список сообщений форума');
define('MSG_msg_saved','Сообщения успешно сохранены');
define('MSG_opt_go','Вернуться к настройкам форума');
define('MSG_opt_saved','Настройки форума успешно сохранены');
define('MSG_query_done','SQL-запрос выполнен');
define('MSG_query_go','Выполнить еще один SQL-запрос');
define('MSG_quick_template','шаблон промежуточных сообщений');
define('MSG_rules_foredit','для редактирования правил форума');
define('MSG_rules_go','Вернуться к редактированию правил форума');
define('MSG_rules_saved','Правила форума успешно сохранены');

define('MSG_template_go','Вернуться к редактированию шаблона');
define('MSG_template_saved','Шаблон успешно сохранен');
define('MSG_top_counters','Верхние счетчики');
define('MSG_u_basiclevel','Основной уровень пользователя');
define('MSG_u_delete','Вы действительно хотите удалить пользователя');
define('MSG_u_go','Выбрать другого пользователя для редактирования');
define('MSG_u_rights_set','Права доступа пользователя успешно сохранены');
define('MSG_u_do_delete','Удалить пользователя');
define('MSG_u_deletename','Имя пользователя, которого следует удалить');
define('MSG_u_deloptions','Опции удаления');
define('MSG_u_delmsg','Удалить все сообщения этого пользователя');
define('MSG_u_delguest','Удалить все сообщения незарегистрированных пользователей, которые отправлены от этого имени');
define('MSG_upload_doinstall','Начать установку дополнения');
define('MSG_upload_go','Загрузить еще смайлик или аватар');

define('MSG_irc_server','Адрес IRC-сервера');
define('MSG_irc_channel','IRC-канал');

define('MSG_sys_passchanged','Пароль пользователя System изменен');
define('MSG_sys_logout','Выйти из Центра Администрирования');
define('MSG_sys_passchange','Смена пароля пользователя System');
define('MSG_sys_oldpass','Введите пароль пользователя System');
define('MSG_sys_newpass','Введите новый пароль');
define('MSG_sys_newpass_confirm','Введите новый пароль еще раз для подтверждения');

define('MSG_user_activate','Активировать');
define('MSG_user_unban','Вернуть');
define('MSG_user_ban','Изгнать');
define('MSG_user_clearing','Очистка неактивных пользователей');
define('MSG_user_lvdays','Посетивших форум не менее ');
define('MSG_user_pcount','Отправивших не более ');
define('MSG_user_lpdays','Отправивших сообщение не менее');
define('MSG_user_daysago','дней назад');
define('MSG_user_cleardecr','Все условия объединяются по логическому И. Если поле незаполнено, условие игноируется');
define('MSG_user_bannedlist','Список изгнанных с форума пользователей');
define('MSG_user_inactivelist','Список неактивных пользователей');
define('MSG_user_noinactive','Неактивных пользователей на форуме нет');
define('MSG_user_nobanned','Изгнанных пользователей на форуме нет');
define('MSG_user_saved','Изменения в профиле сохранены');
define('MSG_user_backlist','Назад к списку пользователей');
define('MSG_user_created','Пользователь успешно создан');
define('MSG_user_delavatar','Удалить аватар пользователя');
define('MSG_user_disallow_edit','Запретить пользователю редактирование собственного профиля');
define('MSG_user_canonized','Канонизация имен пользователей прошла успешно');
define('MSG_user_only_inactive','Только не активных');

define('MSG_uw_params','Параметры для вывода предупреждений/поощрений');
define('MSG_uw_users','Имена пользователей, для которых следует выводить предупреждения/поощрения');
define('MSG_uw_users_descr','Имена пользователей следует разделять запятой. Если ни одного имени не указано, будут выбраны все пользователи');
define('MSG_uw_onlyactive','Выводить только предупреждения, которые действуют сейчас');
define('MSG_uw_list','Список предупреждений/поощрений');
define('MSG_uw_deleted','Предупреждение удалено');
define('MSG_uw_list','Вернуться к списку предупреждений/удалений');

define('MSG_css_font_family','Название шрифта.');
define('MSG_css_font_style','Стиль шрифта: normal - обычный, italic - курсив, oblique - наклонный.');
define('MSG_css_font_variant','Начертание шрифта: normal - обычный, small-caps - все буквы как заглавные');
define('MSG_css_font_weight','Жирность шрифта: normal - обычный, bold - полужирный, bolder - жирный, lighter - менее жирный, а также числовые значения в диапазоне от 0 до 1000.');
define('MSG_css_font_size','Размер шрифта в пунктах.');
define('MSG_css_color','Цвет текста или элемента.');
define('MSG_css_background_color','Цвет фона.');
define('MSG_css_text_decoration','Эффекты шрифта: none - нет, underline - подчеркнутый, line-through - зачеркнуый, overline - надчеркнутый.');
define('MSG_css_text_align','Вырванивание текста по горизонтали: left-по левому краю, right - по правому краю, center - по центру, justify - по ширине');
define('MSG_css_border','Граница объекта. Описание состоит из трех частей: ширина, цвет, тип.');
define('MSG_css_text_transform','Преобразование регистра: none - нет, capitalize - сделать заглавными первые буквы слов, uppercase - все буквы заглавные, lowercase - все буквы строчные.');
define('MSG_css_margin','Отступы снаружи от края объекта.');
define('MSG_css_padding','Отступы текста внутри объекта относительно его края');

define('MSG_backup_title','Создание резервной копии базы данных');
define('MSG_backup_mode','Способ сжатия');
define('MGS_backup_nocomp','Нет');
define('MSG_backup_gzip','Сжатие GZIP');
define('MSG_backup_bzip','Сжатие BZIP');
define('MSG_backup_start','Создать резервную копию');
define('MSG_backup_now','Выполнить сейчас');
define('MSG_backup_last','Последнее резервное копирование');
define('MSG_backup_process','Создается резервная копия базы данных. Это может занять некоторое время.');
define('MSG_backup_files','Файлы резервных копий');
define('MSG_backup_delete','Вы действительно хотите удалить файл с резервной копией');
define('MSG_backup_deleted','Резервная копия удалена!');

define('MSG_convert_next','Преобразовать следующую порцию файлов');
define('MSG_bcodes_list','Список пользовательских BoardCode');
define('MSG_bcodes_saved','Пользовательские коды BoardCode сохранены');
define('MSG_go_bcodes','Вернутся к редактированию кодов');
define('MSG_bcodes_descr','Введенный код обрабатывается с помощью PHP-функции preg_replace("/код/si","замена",$text). Символы [,] и / экранируются автоматически. Для выделения подстроки внтури тега используйте (.*?), для вставки этой подстроки -- $1, $2 и т.д. Например, если задано выражение [test](.*?)[/test], а в качестве строки замены Testing:$1, перед строкой внутри тега [test], будет вставляться "Testing:".');
define('MSG_bcodes_regexp','Регулярное выражение');
define('MSG_bcodes_replace','Строка замены');

define('MSG_ipban_list','Список адресов, с которых запрещен доступ');
define('MSG_ipban_descr','Вы можете указать как отдельный адрес (его нужно прописать в левом столбце), так и диапазон адресов (в этом случае в левом столбце пишется начальный адрес, в правом -- конечный)');
?>