<?

define('MSG_bmk_added','Тема успешно добавлена в закладки');
define('MSG_bmk_deleted','Всего удалено закладок: ');
define('MSG_bmk_list','Список закладок');

define('MSG_g_message','Заявка на вступление в группу');
define('MSG_g_adduser','Добавить участника');
define('MSG_g_message_send','Заявка на вступление в группу отправлена модератору');
define('MSG_g_joined','Вы вступили в группу');
define('MSG_g_quited','Вы вышли из группы');
define('MSG_g_added','Пользователь добавлен в группу');
define('MSG_g_deleted','Пользователь удален из группы');
define('MSG_g_sent','Сообщение было отправлено всем пользователям, входящим в группу');
define('MSG_g_groups','Группы пользователей');
define('MSG_g_view','Просмотр группы');
define('MSG_g_request_join','Отправка заявки на вступление в группу');

define('MSG_go_back','Вернуться на предыдущую страницу');
define('MSG_go_mainpage','Перейти на главную страницу');
define('MSG_go_choose','Теперь вы можете выбрать одно из следующих действий:');
define('MSG_go_topic','Вернуться к предыдущей теме');
define('MSG_go_forum','Вернуться к списку тем в разделе');
define('MSG_go_mainpage_short','Главная страница');
define('MSG_go_updated','Перейти к списку обновившихся тем');
define('MSG_to_newpost','Перейти к списку непрочитанных тем');
define('MSG_go_top','Наверх');

define('MSG_e','Ошибка');

define('MSG_e_mes','Если ошибка возникает часто, <a href="feedback.php">сообщите</a> нам об этом.');

define('MSG_e_bmk_noguests','Гостям не разрешается создавать закладки!');
define('MSG_e_bmk_alreadyexists','Эта тема уже добавлена в закладки');
define('MSG_e_ab_noguests','Гостям запрещено пользоваться функциями адресной книги');
define('MSG_e_badpassword','Неправильно введен пароль!');
define('MSG_e_nomodule','Не найден модуль ');
define('MSG_e_nomail','Не найден файл с шаблоном Email-сообщения!');
define('MSG_e_badcode','Неправильно введен защитный код');
define('MSG_e_av_badfilesize','Аватар имеет слишком большой размер!');
define('MSG_e_av_badtype','Неверный тип файла аватара или он поврежден при загрузке');
define('MSG_e_av_badsize','Аватар имеет слишком большой размер!');
define('MSG_e_f_notexists','Раздела с таким номером не существует или он недоступен для просмотра!');
define('MSG_e_f_closed','Данный раздел закрыт. Отправка соощений невозможна');
define('MSG_e_f_noscript','Не указан путь к включаемому скрипту');
define('MSG_e_t_notexists','Темы с таким номером не существует!');
define('MSG_e_t_closed','Невозможно отправить сообщение в данную тему, т.к. она является закрытой!');
define('MSG_e_t_norights','У вас недостаточный уровень для создания темы');
define('MSG_e_t_empty','Название темы не может быть пустым!');
define('MSG_e_t_rated','Вы уже рейтинговали данную тему!');
define('MSG_e_t_rnoguest','Гостям не разрешается рейтинговать темы!');
define('MSG_e_t_badvalue','Неправильное значение для рейтинга!');
define('MSG_e_f_norightsread','У вас недостаточно прав для чтения сообщений в данном разделе');
define('MSG_e_p_norights','У вас недостаточно прав для отправки сообщения');
define('MSG_e_p_notfound','Сообщение с указанным номером не найдено');
define('MSG_e_p_noeditrights','У вас недостаточно прав для редактирования этого сообщения');
define('MSG_e_p_empty','Текст сообщения не может быть пустым!');
define('MSG_e_p_toobig','Файл-приложение имеет слишком большой размер!');
define('MSG_e_p_onlypics','В данном разделе разрешается прикреплять только картинки!');
define('MSG_e_p_flood','После отправки вашего предыдущего сообщения слишком мало времени');
define('MSG_e_p_norightsattach','У вас недостаточно прав для прикрепления файла к сообщению!');
define('MSG_e_p_emptycomplain','Текст сообщения о нарушении правил не может быть пустым!');
define('MSG_e_p_reguser','На форуме существует зарегистрированный пользователь с таким именем. Отправьте сообщение от другого имени!');
define('MSG_e_p_toosmall','Сообщение имеет длину меньше минимально допустимой');
define('MSG_e_p_toolarge','Длина сообщения превышает максимально допустимую');
define('MSG_e_p_nocomplain','Функция жалобы модератору отключена');
define('MSG_e_ph_badfile','Фотография не является JPEG-файлом или повреждена');
define('MSG_e_ph_badfilesize','Фотография имеет слишком большой объем!');
define('MSG_e_ph_badsize','Размеры фотографии превышают максимально допустимые!');
define('MSG_e_ph_badtype','Неверный тип файла фотографии или она повреждена при загрузке');
define('MSG_e_ph_toolarge','Слишком большой размер файла с фотографией');
define('MSG_e_u_noname','Вы не ввели имя пользователя!');
define('MSG_e_u_passnotmatch','Введенный пароль не совпадает с подтверждением!');
define('MSG_e_u_reservedname','Запрещается использование зарезервированных системых имен: Guest, System, NewUser');
define('MSG_e_u_alreadyused','Пользователь с таким или очень похожим именем или тем же адресом e-mail уже существует на форуме!');
define('MSG_e_u_badoldpass','Неправильно введен старый пароль!');
define('MSG_e_u_nosuchuser','Пользователя с таким именем не существует!');
define('MSG_e_u_filldata','Вам необходимо заполнить хотя бы одно поле для восстановления пароля!');
define('MSG_e_u_notfound','Пользователь с такими данными не найден на форуме!');
define('MSG_e_u_sysuser','Вы не можете получить пароль для системных пользователей!');
define('MSG_e_u_badkey','Неправильно указан ключ для активации пароля!');
define('MSG_e_u_sysprofile','Вы не можете редактировать профили системных пользователей: Guest,System,NewUser!');
define('MSG_e_u_rated','Вы уже изменяли рейтинг данного пользователя!');
define('MSG_e_u_guest_no_rate','Гостям не разрешается изменять рейтинги участников!');
define('MSG_e_u_emptypass','Пароль пользователя не может быть пустым!');
define('MSG_e_u_cyrforbidden','В имени пользователя есть запрещенные символы!');
define('MSG_e_u_guestnosend','Гостям не разрешается отправлять сообщения по почте!');
define('MSG_e_u_noactivation','На данном форуме активацию пользователей может осуществлять только Администратор');
define('MSG_e_u_badchars','Ваше имя содержит недопустимые символы: запятую (,) или точку с запятой (;)');
define('MSG_e_u_inactive','Ваш аккаунт неактивен. Обратитесь к администрации форума за разъяснениями');
define('MSG_e_u_emptymail','Не указан адрес E-mail');
define('MSG_e_u_avatarurl','Неправильно указан URL аватара');
define('MSG_e_u_alreadyactive','Ваш профиль уже активирован. Вы можете зайти на форум обычным способом');
define('MSG_e_u_selfrate','Вы не можете рейтинговать сами себя!');
define('MSG_e_u_level_rate','У вас недостаточный уровень для изменения рейтинга пользователя!');
define('MSG_e_u_encrypt_change','Вы не можете изменить режим шифрования без изменения пароля!');
define('MSG_e_u_nouser_resend','Нет такого пользователя или он уже активирован!');
define('MSG_e_u_badactmode','На форуме не включен режим активации через Email!');
define('MSG_e_u_regblocked','С данного IP-адреса уже была произведена регистрация. Повторно зарегистрироваться можно будет только через 30 секунд');
define('MSG_e_u_noedit','Вам запрещено редактирование вашего профиля! Обратитесь к администрации за разъяснениями');
define('MSG_e_u_noblogguest','Гостям запрещено создавать блоги!');
define('MSG_e_u_nobloglevel','У вас недостаточный уровень для создания блога!');
define('MSG_e_u_noblogguest','Гостям запрещено создавать личные галереи!');
define('MSG_e_u_nobloglevel','У вас недостаточный уровень для создания личной галереи!');
define('MSG_e_u_badword','Ваш логин содержит запрещенные слова!');
define('MSG_e_u_norateperiod','С момента отправки вами последнего сообщения прошло слишком много времени. Вы не можете влиять на рейтинг, пока не напишете что-нибудь на форум.');
define('MSG_e_v_norights','У вас недостаточно прав для создания голосования!');
define('MSG_e_v_norightsvote','У вас недостаточно прав для того, чтобы проголосовать!');
define('MSG_e_v_already','Вы уже голосовали в данном опросе!');
define('MSG_e_v_novariant','Вы не выбрали вариант для голосования');
define('MSG_e_pm_noguests','Гостям не разрешается пользоваться внутренними сообщениями!');
define('MSG_e_pm_empty','Сообщение не может содержать пустую тему или пустой текст!');
define('MSG_e_pm_ignored','Данный пользователь внес вас в список игнорируемых. Вы не можете отправлять ему сообщения!');
define('MSG_e_pm_banned','Изгнанным пользователям запрещается писать личные сообщения. Если вы хотите связаться с администрацией форума, воспользуйтесь ссылкой "Обратная связь" в главном меню');
define('MSG_e_mod_norights','У вас нет прав для модерирования данного раздела');
define('MSG_e_mod_subordinate','Вы не можете редактировать или удалять сообщения пользователей с более высокими правами');
define('MSG_e_mod_noparams','Вы не указали параметры очистки раздела');
define('MSG_e_mod_notopicrights','У вас нет прав для создания темы в том разделе, куда вы хотите перенести тему!');
define('MSG_e_mod_singlepost','Данная тема содержит единственное сообщение и поэтому не может быть разбита!');
define('MSG_e_warn_nocomment','Вы не можете выносить предупреждение, не обосновав причину');
define('MSG_e_warn_value','Неправильно указано значение предупреждения');
define('MSG_e_sub_noguest','Гостям не разрешается подписываться на темы!');
define('MSG_e_sub_already','Вы уже подписаны на данную тему!');
define('MSG_e_sub_none','Вы не можете отписаться от данной темы - вы на нее не подписаны!');
define('MSG_e_sub_badkey','Неправильный ключ пользователя для подписки/отписки!');
define('MSG_e_g_noguests','Гостям не разрешается просматривать группы участников!');
define('MSG_e_g_norights','У вас недостаточно прав для выполнения этого действия!');
define('MSG_e_g_alreadyadded','Данный пользователь уже является участником этой группы');
define('MSG_e_mail_empty','Текст Email-сообщения не может быть пустым');
define('MSG_e_mail_emptysubj','Тема Email-сообщения не может быть пустой');
define('MSG_e_mail_guests','Гостям не разрешается отправлять Email-сообщения');
define('MSG_e_new_noguest','Гостям не разрешается просматривать список новых сообщений');
define('MSG_e_misc_unfilled','Все поля формы должны быть заполнены!');
define('MSG_e_a_emptytext','Текст статьи не может быть пустым!');
define('MSG_e_a_emptytitle','Название статьи не может быть пустым');
define('MSG_e_a_noauthor','Не указан автор статьи!');
define('MSG_e_dl_emptytext','Описание файла не может быть пустым!');
define('MSG_e_dl_emptytitle','Название файла не может быть пустым!');
define('MSG_e_dl_nohomepage','Не указана домашняя страница файла!');
define('MSG_e_dl_nourl','Не указан URL для скачивания!');
define('MSG_e_dl_homepage','Некорректный URL для домашней страницы файла!');
define('MSG_e_dl_url','Некорректный URL для скачивания файла!');
define('MSG_e_n_emptytext','Текст новости не может быть пустым!');
define('MSG_e_n_emptytitle','Заголовок новости не может быть пустым!');
define('MSG_e_u_ipchanged','У вас изменился IP-адрес! Войдите на форум заново');
define('MSG_e_quote','Выделите мышкой текст, который хотите процитировать, после чего нажимте ссылку "Цитировать" еще раз!');
define('MSG_e_f_norightstopic','Недостаточно прав для создания темы');
define('MSG_e_u_noextavatardata','Не указаны размеры внешнего аватара');
define('MSG_e_u_extavatarsize','Размеры внешнего аватара превышают допустимые');
define('MSG_e_mod_sametopic','Номер темы-получаетеля совпадает с номером исходной');
define('MSG_e_mod_noforumsplit','Форума с таким номером не существует или у вас недостаточно прав доступа для отправки сообщения');
define('MSG_e_search_nodata','Не заданы критерии для поиска');
define('MSG_e_nowrite','Файл или каталог недоступен на запись: ');
define('MSG_e_closed_status','Форум временно закрыт администратором');

define('MSG_dl_file','Файл для загрузки на сервер');
define('MSG_dl_filedescr','Если вы загружаете файл со своего компьютера, URL вводить не обязательно');
define('MSG_dl_publisher','Файл закачал');

define('MSG_friend_sent','Сообщение отправлено');

define('MSG_last','В течение последних');

define('MSG_m1','минуту');
define('MSG_m2','минуты');
define('MSG_m3','минут');

define('MSG_f','Раздел');

define('MSG_lm1','за последнюю');
define('MSG_lm2','за последние');
define('MSG_lm3','за последние');

define('MSG_na','Нет');
define('MSG_and','и');

define('MSG_misc_bcode','Использование BoardCode');
define('MSG_misc_smiles','Список смайликов');
define('MSG_misc_sendfriend','Сообщить другу');
define('MSG_misc_tsearch_result','Результаты поиска темы');
define('MSG_misc_tsearch','Поиск темы');
define('MSG_misc_tsearch_title','Слова из названия или описания темы');
define('MSG_misc_tsearch_forum','Искать в разделе');
define('MSG_misc_extcode','Расширенные коды BoardCode');
define('MSG_misc_nocode','Внутри текста, помещенного в тег [nocode] не производится обработка BoardCode.');
define('MSG_misc_nohtml','HTML-код внутри тега [nohtml] отображается в виде текста.');
define('MSG_misc_cut','Текст внутри тега [cut] отображается только если пользователь перейдет по ссылке. Расширенная форма [cut="Text"] позволяет задавать текст этой ссылки');
define('MSG_misc_hide','Текст внутри тега [hide] виден только пользователям, набравшим более Number сообщений (сообщения считаются только по разделам, для которых включена статистика)');
define('MSG_misc_level','Текст внутри тега [level] виден только пользователям, уровень которых не ниже Level');
define('MSG_misc_tsearch_none','Подходящих тем не найдено');

define('MSG_mod_join','Объединение тем');
define('MSG_mod_split','Разбиение темы');
define('MSG_mod_topic','Модерирование темы');
define('MSG_mod_joined','Темы успешно объединены');
define('MSG_mod_t_saved','Параметры тем сохранены');
define('MSG_mod_moved','перемещено');
define('MSG_mod_deleted','удалено');
define('MSG_mod_saved','Параметры темы сохранены');
define('MSG_mod_complain','Жалоба на нарушение правил в сообщении');
define('MSG_mod_complain_send','Жалоба отправлена');
define('MSG_mod_topic_deleted','Тема удалена');
define('MSG_mod_bancleared','Пользователь удален из списка изгнанных в данном разделе');
define('MSG_mod_banned','Пользователь изгнан из данного раздела');
define('MSG_mod_unban','Вернуть');
define('MSG_mod_ban','Изгнать');
define('MSG_mod_nobanned','В разделе нет изгнанных пользователей');
define('MSG_mod_banuser','Изгнать пользователя');
define('MSG_mod_banname','Введите имя пользователя, которого надо изгнать');
define('MSG_mod_premod','Премодерация раздела');
define('MSG_mod_voteview','Просмотр результатов опроса');
define('MSG_mod_votedfor','проголосовал за');
define('MSG_mod_topic','Модерирование раздела');
define('MSG_mod_clear','Очистка раздела');
define('MSG_mod_splitnew','Вынести сообщения в новую тему');
define('MSG_mod_splitadd','Добавить в уже существующую тему');
define('MSG_mod_topicnumber','Номер темы, к которой следует присоединить отделяемые сообщения');
define('MSG_mod_searchtopic','Поиск темы');
define('MSG_mod_putlink','Добавить ссылку с сообщением о том, что тема была выделена');
define('MSG_mod_copy','Копировать тему');
define('MSG_mod_copied','Тема успешно скопирована');
define('MSG_mod_pcopied','скопировано');
define('MSG_mod_nouser','Пользователь не найден');

define('MSG_p1','сообщение');
define('MSG_p2','сообщения');
define('MSG_p3','сообщений');

define('MSG_pl1','опрос');
define('MSG_pl2','опроса');
define('MSG_pl3','опросов');

define('MSG_pm1','новое сообщение');
define('MSG_pm2','новых сообщения');
define('MSG_pm3','новых сообщений');
define('MSG_pmnew1','новое');
define('MSG_pmnew2','новых');
define('MSG_pmnew3','новых');
define('MSG_pm','Список личных сообщений по темам');
define('MSG_pm_sended','Сообщение успешно отправлено');
define('MSG_pm_draft','Сообщение сохранено в Черновиках');
define('MSG_pm_inbox','Входящие');
define('MSG_pm_outbox','Отправленные');
define('MSG_pm_drafts','Черновики');
define('MSG_pm_archive','Архив');
define('MSG_pm_reply','Отправка ответа');
define('MSG_pm_view','Просмотр сообщения');
define('MSG_pm_deleted','Сообщение удалено');
define('MSG_pm_deleted_all','Все сообщения удалены');
define('MSG_pm_moved','Сообщение перенесено в архив');
define('MSG_pm_new','Новое!');
define('MSG_pm_nosubject','Без темы');
define('MSG_pm_correspondent','Корреспондент');
define('MSG_pm_count','Количество сообщений');
define('MSG_pm_unread','Количество непрочитанных');
define('MSG_pm_startdate','Дата начала переписки');
define('MSG_pm_lastdate','Дата окончания переписки');
define('MSG_pm_subj_list','Количество сообщений по теме');

define('MSG_pages','Страницы: ');

define('MSG_preview','Предварительный просмотр');

define('MSG_search','Поиск по форуму');
define('MSG_search_posts','Результаты поиска сообщений, содержащих');
define('MSG_search_user','Результаты поиска сообщений пользователя');
define('MSG_search_nogrp','не группировать сообщения по разделам');
define('MSG_search_help','Дополнительные возможности поиска');
define('MSG_search_help_plus','+слово - искать сообщения, в которых обязательно есть слово');
define('MSG_search_help_minus','-слово - искать сообщения, в которых данного слова нет');
define('MSG_search_help_trunc','слов* - искать все слова, начинающиеся на "слов"');
define('MSG_search_help_tilde','~слово - сообщения, где есть указанное слово, обладают меньшей релевантностью');
define('MSG_search_help_quotas','"слово1 слово2" - искать последовательность из слова1 и слова2, стоящих подряд');
define('MSG_search_help_bracket','Группировать операции и задавать их приоритет можно с помощью скобок');
define('MSG_search_tooshort','Длина поискового запроса должна быть не менее 4 букв');
define('MSG_search_authored_by','созаднных');
define('MSG_search_usertopic','Результаты поиска тем пользователя');
define('MSG_search_more1','Возможно, сообщений, соответствующих заданному критерию, больше, однако в результатах поиска показвыаются только первые ');
define('MSG_search_more2','Задайте более жесткие критерии поиска, чтобы найти остальные сообщения');

define('MSG_sub_subscribed','Вы успешно подписаны на тему');
define('MSG_sub_unsubscribed','Вы успешно отписались от темы');
define('MSG_sub_saved','Параметры подписки сохранены');
define('MSG_sub_params','Параметры подписки');
define('MSG_subscr_unsub_all','Отписаться от всего');
define('MSG_subscr_unsub_notify','Отписаться от уведомлений о создании новых тем');
define('MSG_subscr_unsub_auto','Отменить автоматическую подписку на новые темы');
define('MSG_subscr_unsub_topics','Отписаться от всех существующих тем');
define('MSG_subscr_sub_notify','Подписаться на уведомления о создании новых тем');
define('MSG_subscr_sub_auto','Включить автоматическую подписку на новые темы');
define('MSG_subscr_sub_topics','Подписаться на все существующие темы');
define('MSG_subscr_sub_all','Подписаться на все темы и уведомления');


define('MSG_t1','тема');

define('MSG_t2','темы');

define('MSG_t3','тем');

define('MSG_t_done','Тема успешно создана');
define('MSG_t_create','Создание новой темы');
define('MSG_t_creating','Создание новой темы');
define('MSG_t_rated','Ваш голос учтен в рейтинге темы');
define('MSG_t_forprint','Печать');
define('MSG_t_nonew','Тема не содержит непрочитанных сообщений');
define('MSG_t_new','Тема содержит непрочитанные сообщения');
define('MSG_t_hot','"Горячая" тема, содержащая непрочитанные сообщения');
define('MSG_t_closednew','Закрытая тема, содержащая непрочитанные сообщения');
define('MSG_t_closedhot','Закрытая "горячая" тема, содержащая непрочитанные сообщения');
define('MSG_t_vote','Тема включает в себя опрос');
define('MSG_t_lastposter','последнее сообщение отправил');
define('MSG_t_lasts','Последние');
define('MSG_t_actives','Самые активные');
define('MSG_t_per','по');
define('MSG_t_perpage','тем на странице');
define('MSG_t_filterby','Фильтровать по наличию');
define('MSG_t_msgsplitted1','Часть сообщений этой темы была выделена в тему');
define('MSG_t_msgsplitted2','Эта тема была выделена из темы');
define('MSG_t_msgjoin','К данной теме присоединена тема ');
define('MSG_t_deleted','Тема удалена');
define('MSG_t_premoderation','Премодерация темы');
define('MSG_t_viewvote','Лог голосования');
define('MSG_t_unanswered_show','Показать список тем без ответов');
define('MSG_t_unanswered','Темы без ответов');
define('MSG_t_updated','Обновившиеся темы');
define('MSG_t_noupdtopics','С вашего последнего визита ни одна тема не обновилась');
define('MSG_t_unmarked','Отметка о прочтении темы снята');
define('MSG_t_mark_unread','Снять отметку о прочтении');
define('MSG_t_link','Частичный URL темы (должен содержать только латинские буквы, цифры, прочерк и минус)');
define('MSG_t_link_descr','Если это поле незаполнено или заполнено неправильно, частичным URL будет порядковый номер темы');

define('MSG_u1','пользователь');
define('MSG_u2','пользователя');
define('MSG_u3','пользователей');

define('MSG_v1','посетитель');
define('MSG_v2','посетителя');
define('MSG_v3','посетителей');

define('MSG_uv1','просмотрел');
define('MSG_uv2','просмотрели');
define('MSG_uv3','просмотрели');

define('MSG_uh1','скрытый пользователь');
define('MSG_uh2','скрытых пользователя');
define('MSG_uh3','скрытых пользователей');

define('MSG_ug1','гость');
define('MSG_ug2','гостя');
define('MSG_ug3','гостей');

define('MSG_u_registered','Пользователь успешно зарегистрирован');
define('MSG_u_loggedin','Вы успешно вошли на форум');
define('MSG_u_logout','Вы вышли с форума');
define('MSG_u_changed','Профиль пользователя успешно изменен');
define('MSG_u_register','Регистрация пользователя');
define('MSG_u_editprofile','Редактирование профиля');
define('MSG_u_rules','Правила форума');
define('MSG_u_list','Список участников форума');
define('MSG_u_profile_view','Просмотр профиля участника');
define('MSG_u_password','Восстановление забытого пароля');
define('MSG_u_pass_sent','Пароль был отправлен на E-mail, указанный в профиле');
define('MSG_u_pass_generated','Письмо с инструкцией для активации нового пароля отправлено на E-mail, указанный в профиле');
define('MSG_u_pass_activated','Пароль успешно активирован');
define('MSG_u_online','Присутствующие на форуме пользователи');
define('MSG_u_rated','Ваш голос учтен. Через некоторое время вы снова можете проголосовать за этого пользователя');
define('MSG_u_confirm','Подтверждение регистрации');
define('MSG_u_need_activate','Вам необходимо активировать аккаунт нового пользователя из Центра Администрирования');
define('MSG_u_needactivate','Для окончательной регистрации на форуме вам необходимо активировать ваш аккаунт. Информация о том, как это сделать, выслана на указанный вами Email');
define('MSG_u_needadminactivate','Вы зарегистрированы на форуме. В ближайшее время ваш аккаунт будет активирован администратором');
define('MSG_u_newuser','Новый пользователь зарегистрировался!');
define('MSG_u_orderby','Сортировать по');
define('MSG_u_regdate','дате регистрации');
define('MSG_u_name','имени');
define('MSG_u_title','званию');
define('MSG_u_level','уровню доступа');
define('MSG_u_pcount','количеству сообщений');
define('MSG_u_gender','половому признаку');
define('MSG_u_location','месту жительства');
define('MSG_u_icq','ICQ');
define('MSG_u_homepage','домашней странице');
define('MSG_u_lastvisit','последнему визиту');
define('MSG_u_order','выводить');
define('MSG_u_warnlist','Список предупреждений и поощрений для пользователя');
define('MSG_u_greetings','Привет');
define('MSG_u_tcount','количеству созданных тем');
define('MSG_u_urating','рейтингу пользователя');
define('MSG_u_trating','рейтингу созданных тем');
define('MSG_u_tviews','количеству просмотров созданных тем');
define('MSG_u_levelconfirm','Вы действительно хотите удалить этот уровень доступа');
define('MSG_u_changeconfirm','Вы изменили адрес Email и теперь необходимо подтвердить, что вы имеете к нему доступ. Инструкция, как это сделать, была выслана на новый адрес Email');
define('MSG_u_changemail','Подтверждение смены почтового адреса');
define('MSG_u_blogsaved','Параметры блога сохранены');
define('MSG_u_gallerysaved','Параметры личной галереи сохранены');
define('MSG_u_changegallery','Изменение настроек личной галереи');
define('MSG_u_changeblog','Изменение настроек личного блога');
define('MSG_u_viewblog','Блог пользователя');
define('MSG_u_viewgallery','Личная фотогалерея пользователя');
define('MSG_u_ignoreforums','Игнорируемые разделы');

define('MSG_vt1','голосовании');

define('MSG_vt2','голосованиях');

define('MSG_vt3','голосованиях');

define('MSG_view_mainpage','Просматривает главную страницу');
define('MSG_view_topic','Просматривает тему');
define('MSG_view_inforum','в разделе');
define('MSG_view_forum','Просматривает раздел');
define('MSG_view_dopost','Отправляет сообщение в тему');
define('MSG_view_dotopic','Создает новую тему в разделе');
define('MSG_view_rules','Просматривает правила');
define('MSG_view_before_register','форума перед регистрацией');
define('MSG_view_registering','Проходит процесс регистрации');
define('MSG_view_registered','Завершил регистрацию');
define('MSG_view_logging_in','Входит на форум');
define('MSG_view_logged_in','Вошел на форум');
define('MSG_view_logged_out','Вышел с форума');
define('MSG_view_profile','Просматривает профили пользователей');
define('MSG_view_userlist','Просматривает список пользователей');
define('MSG_view_online','Просматривает список присутствующих на форуме');
define('MSG_view_start_search','Вводит запрос для поиска');
define('MSG_view_search_topic','Просматривает результаты поиска темы');
define('MSG_view_search_post','Просматривает результаты поиска сообщения');
define('MSG_view_search_user','Просматривает результаты поиска участника');
define('MSG_view_updated','Просматривает обновившиеся сообщения');
define('MSG_view_newpost','Просматривает непрочитанные сообщения');
define('MSG_view_undescribed','Совершает неописуемое действие');

define('MSG_your_bookmarks','Ваши закладки');
define('MSG_t_title','Название темы');
define('MSG_t_count','Сообщения');
define('MSG_t_views','Просмотры');
define('MSG_t_start','Начало');
define('MSG_t_last','Последнее сообщение');
define('MSG_t_descr','Описание темы');
define('MSG_t_sticky','Тема является приклеенной');
define('MSG_t_stickypost','Показывать первое сообщение на каждой странице');
define('MSG_t_closed','Тема закрыта');
define('MSG_t_israted','Тема участвует в рейтинге');
define('MSG_t_rating','Рейтинг');
define('MSG_t_moderate','Модерировать');
define('MSG_t_currating','Текущий рейтинг темы');
define('MSG_t_rate','Оценить тему');
define('MSG_t_dorate','Оценить');
define('MSG_t_tobookmark','В закладки');
define('MSG_t_subscribe','Подписаться');
define('MSG_t_unsubscribe','Отписаться');
define('MSG_t_mailtofriend','Сообщить другу');
define('MSG_t_msgorder','Выводить сообщения ');
define('MSG_t_reverse','в обратном порядке');
define('MSG_t_normal','в обычном порядке');
define('MSG_t_join','Объединить тему');
define('MSG_t_split','Разбить тему');
define('MSG_t_print','Версия для печати');
define('MSG_t_premoderated','Тема успешно создана. Она станет доступной после проверки модератором');

define('MSG_delete','Удалить');
define('MSG_rating','Рейтинг');
define('MSG_no_bookmarks','У вас нет личных закладок');
define('MSG_maxfile','Макс. размер файла');

define('MSG_user_groups','Группы участников');
define('MSG_g_title','Название');
define('MSG_g_your_status','Ваш статус');
define('MSG_actions','Действия');
define('MSG_g_request','Отправлена заявка на вступление');
define('MSG_g_member','Участник');
define('MSG_g_coord','Координатор');
define('MSG_g_count','Количество пользователей');

define('MSG_g_join','Вступить');
define('MSG_g_send_request','Подать заявку');
define('MSG_g_quit','Выйти');
define('MSG_g_none','На данный момент на форуме не существует групп или они недоступны для просмотра');
define('MSG_g_requestjoin','Заявка на вступление в группу');
define('MSG_g_request_text','Текст заявки');

define('MSG_all_time','все время');
define('MSG_last_day','последние сутки');
define('MSG_last_2days','последние двое суток');
define('MSG_last_week','последнюю неделю');
define('MSG_last_month','последний месяц');
define('MSG_last_year','последний год');

define('MSG_g_info','Информация о группе');
define('MSG_g_allowjoin','Принять в группу');
define('MSG_g_deletefrom','Удалить из группы');
define('MSG_g_mailsend','Рассылка почтового сообщения по группе');
define('MSG_g_forcejoin','Добавить пользователя в группу');
define('MSG_g_mailtext','Текст сообщения');

define('MSG_a_register','Регистрация');
define('MSG_a_login','Войти');
define('MSG_a_users','Участники');
define('MSG_a_online','Присутствующие');
define('MSG_a_search','Поиск');
define('MSG_a_profile','Профиль');
define('MSG_a_logout','Выйти');
define('MSG_a_bookmarks','Закладки');
define('MSG_a_subscribe','Подписка');
define('MSG_a_pm','Письма');
define('MSG_a_groups','Группы');
define('MSG_a_newposts','Непрочитанные');
define('MSG_a_editcomment','Редактирование комментария');
define('MSG_a_list','Список статей в разделе');
define('MSG_a_updated','Обновившиеся');
define('MSG_a_feedback','Обратная связь');
define('MSG_a_addrbook','Адресная книга');

define('MSG_main_include','включает в себя');
define('MSG_main_lastuser','Последний зарегистрировавшийся пользователь');
define('MSG_main_curtime','Текущее время');
define('MSG_main_lastvisit','Последнее посещение форума');

define('MSG_f_title','Название раздела');
define('MSG_f_count','Темы');
define('MSG_f_lastpost','Последнее сообщение');
define('MSG_f_params','Параметры раздела');
define('MSG_f_descr','Описание раздела');
define('MSG_f_cat','Категория раздела');
define('MSG_f_show_in','Отображать данный раздел как вложенный');
define('MSG_f_inmainpage','На главной странице');
define('MSG_f_levels','Уровни доступа для данного раздела');
define('MSG_f_lview','Уровень для просмотра раздела в списке на главной странице');
define('MSG_f_lread','Уровень для чтения сообщений в разделе');
define('MSG_f_rate','В разделе разрешен рейтинг тем');
define('MSG_f_bcode','В разделе разрешено использование BoardCode');
define('MSG_f_smiles','В разделе разрешено использование графических смайликов');
define('MSG_f_stats','Раздел участвует в подсчете статистики количества сообщений');
define('MSG_f_selfmod','В разделе разрешена модерация собственных тем');
define('MSG_f_attachpics','В разделе разрешено присоединять к сообщениям только картинки');
define('MSG_f_lpost','Уровень для отправки сообщений в раздел');
define('MSG_f_ltopic','Уровень для создания новых тем в разделе');
define('MSG_f_ledit','Уровень для редактирования собственных сообщений в разделе');
define('MSG_f_lpoll','Уровень для создания опросов в разделе');
define('MSG_f_lvote','Уровень для голосования в опросах');
define('MSG_f_lsticky','Уровень для создания приклееных тем');
define('MSG_f_lattach','Уровень для присоединения файлов к сообщениям');
define('MSG_f_lhtml','Уровень для использования HTML в данном разделе');
define('MSG_f_lmoderate','Уровень для модерирования раздела');
define('MSG_f_lip','Уровень для просмотра IP-адресов пользователей');
define('MSG_f_lpremod','Уровень для отправки сообщений без премодерации');
define('MSG_f_ltopicpremod','Уровень для создания тем без премодерации');
define('MSG_f_rules','Правила раздела');
define('MSG_f_sortby','Сортировать темы по');
define('MSG_f_bylast','последнему сообщению');
define('MSG_f_byfirst','времени создания темы');
define('MSG_f_bytitle','названию темы');
define('MSG_f_bystatus','состоянию темы');
define('MSG_f_bycount','количеству сообщений');
define('MSG_f_byviews','количеству просмотров');
define('MSG_f_byrating','рейтингу');
define('MSG_f_byvisit','факту просмотра');
define('MSG_f_moderate','Модерировать раздел');
define('MSG_f_clean','Очистить раздел');
define('MSG_f_close','Закрыть раздел');
define('MSG_f_nonew','В разделе нет непрочитанных сообщений');
define('MSG_f_new','В разделе есть непрочитанные сообщения');
define('MSG_f_editrules','Редактировать правила');
define('MSG_f_rules_edit','Редактирование правил раздела');
define('MSG_f_rules_saved','Правила раздела успешно сохранены');
define('MSG_f_notopics','В данном разделе нет еще ни одной темы. У вас есть шанс стать здесь первым автором!');
define('MSG_f_marked','Сообщения отмечены как прочитанные');
define('MSG_f_newposts','Непрочитанные сообщения');
define('MSG_f_lastvisit','Последнее посещение раздела');
define('MSG_f_notvisited','Вы не посещали данный раздел');
define('MSG_f_marktopics','Отметить все темы раздела как прочитанные');
define('MSG_f_premoderate','Премодерация');
define('MSG_f_premod','На форуме включена премодерация сообщений');
define('MSG_f_chatpresent','Сейчас в чате');
define('MSG_f_nochatpresent','Сейчас в чате никого нет');
define('MSG_f_banusers','Изгнанные пользователи');
define('MSG_f_url','URL внешней ссылки');
define('MSG_f_premoderated','Премодерация раздела успешно выполнена');
define('MSG_f_goto','Быстрый переход в раздел');
define('MSG_f_go','Перейти');
define('MSG_f_msgcount','Количество сообщений');
define('MSG_f_speclevel','Особый уровень доступа');
define('MSG_f_picsonly','только графические файлы');
define('MSG_f_dldir_descr','полный путь к каталогу (см. настройки форума)');

define('MSG_forum_in','форум');
define('MSG_forum_amongthem','В том числе');
define('MSG_forum_exectime','Время выполнения скрипта');
define('MSG_forum_numqueries','Количество выполненных запросов');
define('MSG_forum_querytime','время выполнения запросов');
define('MSG_forum_powered','Форум работает на базе <a href="http://intboard.ru">IntB</a> <a href="http://romark.ru">+</a> <a href="http://www.shmel.org">+</a>');
define('MSG_forum_copyright','');
#Удаление сообщения об авторских правах (ссылок) запрещено лицензией! Допускается видоизменение или перемещение ссылок в соответствии с особенностями дизайна сайта, при условии, что они останутся видимыми и размер шрифта не становится меньше 50% основного шрифта сайта.
define('MSG_forum_rules','Правила форума');
define('MSG_forum_quickreg','Я согласен с правилами, перейти к быстрой регистрации (только базовые сведения)');
define('MSG_forum_fullreg','Я согласен с правилами, перейти к обычной регистрации (заполнение профиля целиком)');
define('MSG_forum_disagree','Я не согласен с правилами');
define('MSG_forum_record','Рекорд посещаемости форума установлен');
define('MSG_forum_record_present','В это время форум одновременно ');
define('MSG_forum_contacts','Контакты');
define('MSG_forum_write_us','По всем вопросам пишите');
define('MSG_forum_now','Сейчас просматривают');
define('MSG_forum_also','а также');
define('MSG_forum_today','За сегодняшний день форум');
define('MSG_including','из них');

define('MSG_input_login','Введите ваш логин');
define('MSG_input_password','Введите ваш пароль');
define('MSG_input_forgot','Забыли пароль');

define('MSG_pm_yours','Ваши личные сообщения');
define('MSG_pm_inbox','Входящие');
define('MSG_pm_ofthem','из них');
define('MSG_pm_sent','Отправленные');
define('MSG_pm_drafts','Черновики');
define('MSG_pm_archive','Архив');
define('MSG_pm_newmsg','Отправить личное сообщение');
define('MSG_pm_list','Список сообщений');
define('MSG_pm_nomsg','В данном ящике нет сообщений');
define('MSG_pm_delete','Удалить выбранные сообщения');
define('MSG_pm_send','Отправка личного сообщения');
define('MSG_pm_subj','Тема сообщения');
define('MSG_pm_receiver','Получатель');
define('MSG_pm_text','Текст исходного сообщения');
define('MSG_pm_options','Опции отправки');
define('MSG_pm_todrafts','Сохранить в черновиках');
define('MSG_pm_pm','Личное сообщение');
define('MSG_pm_sender','Отправитель');
define('MSG_pm_sendtime','Время отправки');
define('MSG_pm_recvtime','Время получения');
define('MSG_pm_answer','Ответить');
define('MSG_pm_toarchive','В архив');
define('MSG_pm_editsend','Редактировать и отправить');
define('MSG_pm_recived','Получено новое личное сообщение');

define('MSG_misc_bcode','Примеры использования BoardCode');
define('MSG_misc_smiles','Графические смайлики, доступные на форуме');
define('MSG_misc_friend','Сообщить другу о теме');
define('MSG_misc_friendname','Имя получателя');
define('MSG_misc_friendaddr','Адрес получателя');
define('MSG_misc_subj','Тема письма');
define('MSG_misc_text','Текст письма');
define('MSG_misc_linkadded','Ссылка на тему будет добавлена автоматически');
define('MSG_misc_mail','Отправка E-mail');
define('MSG_misc_sender','Отправитель');
define('MSG_misc_receiver','Получатель');
define('MSG_misc_detrans','Правила детранслитерации');
define('MSG_misc_caps','Заглавные буквы');
define('MSG_misc_letters','Строчные буквы');
define('MSG_misc_lat','Латиница');
define('MSG_misc_cyr','Кириллица');
define('MSG_misc_nodetrans','Примечание: текст внутри тегов [_ и _] не детранслитерируется');
define('MSG_misc_example','Например текст "`Etot tekst podvergnulsya [_translit_]u" будет детранслитерирован в "Этот текст подвергулся transltу".');
define('MSG_misc_mailsent','Почтовое сообщение успешно отправлено');

define('MSG_mod_topic','Модерирование темы');
define('MSG_mod_action','Действие над темой');
define('MSG_mod_keep','Оставить тему в этом же разделе');
define('MSG_mod_move','Перенести в другой раздел');
define('MSG_mod_delete','Удалить тему');
define('MSG_mod_moveto','Раздел, в который необходимо перенести тему');
define('MSG_mod_voteparams','Параметры голосования');
define('MSG_mod_clean','Очистка раздела');
define('MSG_mod_condition','Введите условия для удаления тем. Все условия объединяются по логическому И, пустые поля игнорируются');
define('MSG_mod_cleandays','Количество дней, прошедших с момента отправки последнего сообщения в тему');
define('MSG_mod_cleancount','Количество соообщений в теме, не более');
define('MSG_mod_cleantitle','Название темы должно содержать');
define('MSG_mod_cleanuser','Тема создана пользователем');
define('MSG_mod_startclean','Очистить');
define('MSG_mod_split','Разбиение темы');
define('MSG_mod_newtitle','Название новой темы');
define('MSG_mod_newdescr','Описание новой темы');
define('MSG_mod_newforum','Раздел новой темы');
define('MSG_mod_posts','Сообщения темы');
define('MSG_mod_dosplit','Разбить');
define('MSG_mod_forum','Модерирование раздела');
define('MSG_mod_moveto2','Раздел, в который будут перенесены выбранные темы');
define('MSG_mod_join','Объединение тем');
define('MSG_mod_addtopic','Добавить тему');
define('MSG_mod_totopic',' в конец темы');
define('MSG_mod_dojoin','Присоединить');
define('MSG_mod_bannedlist','Список изгнанных пользователей в разделе');

define('MSG_vote_question','Вопрос голосования');
define('MSG_vote_beforeend','Количество дней до окончания голосования');
define('MSG_vote_endless','0 - бесконечное голосование');
define('MSG_vote_variant','Вариант голосования');
define('MSG_vote_total','Всего проголосовало');

define('MSG_user_params','Основные параметры профиля');
define('MSG_user_name','Имя пользователя');
define('MSG_user_allowed','Допустимые символы в имени (проверяются с помощью функции preg_match)');
define('MSG_user_oldpass','Введите ваш текущий пароль');
define('MSG_user_change','Это необходимо только в том случае, если вы хотите поменять пароль или e-mail');
define('MSG_user_newpass','Введите новый пароль');
define('MSG_user_emptypass','Если не хотите менять пароль, оставьте это поле пустым');
define('MSG_user_passconfirm','Введите новый пароль еще раз для подтверждения');
define('MSG_user_encrypted','Хранить пароль в зашифрованном виде?');
define('MSG_user_email','Адрес e-mail');
define('MSG_user_emptyemail','Если не хотите менять e-mail, оставьте это поле пустым');
define('MSG_user_showmail','Показывать адрес e-mail другим пользователям');
define('MSG_user_javascript','показывать через JavaScript');
define('MSG_user_picture','В виде картинки');
define('MSG_user_active','Аккаунт активен');
define('MSG_user_lang','Язык форума');
define('MSG_user_style','Стиль форума');
define('MSG_user_signature','Подпись');
define('MSG_user_whatissign','Подпись - это краткое высказывание, которое может добавляться в конец любого вашего сообщения');
define('MSG_user_usesign','Подпись по умолчанию включена');
define('MSG_user_usesigndescr','Эта опция влияет на состояние пункта "использовать подпись" при отправке сообщения');
define('MSG_user_detrans','Применять детранслитерацию автоматически ко всем сообщениям');
define('MSG_user_mails','Получать рассылки от администрации форума и от координаторов групп');
define('MSG_user_sortposts','Порядок сортировки сообщений в темах');
define('MSG_user_sortdefault','Обычный (более ранние - в начале)');
define('MSG_user_sortreverse','Обратный (более поздние - в начале)');
define('MSG_user_smiles','Смайлики по умолчанию включены');
define('MSG_user_smilesdescr','Эта опция влияет на состояние пункта "использовать смайлики" при отправке сообщения');
define('MSG_user_tperpage','Количество тем на странице раздела');
define('MSG_user_mperpage','Количество сообщений на странице темы');
define('MSG_user_aperpage','Количество статей, новостей и файлов на странице');
define('MSG_user_shortdate','Краткий формат даты');
define('MSG_user_datedescr','Формат даты совпадает с форматом функции date в PHP. В формате даты можно использовать следующие символы: <br>j - день месяца<br>D - день недели (краткий)<br>F - полное название месяца<br>G - час в 24-часовой системе<br>i - минуты<br>l - день недели (полностью)<br>m - месяц (цифрами)<br>M - месяц (краткий формат)<br>s - секунды<br>Y - год (4 цифры)<br>y - год (2 цифры)');
define('MSG_user_longdate','Полный формат даты');
define('MSG_user_personalinfo','Персональная информация');
define('MSG_user_gender','Пол');
define('MSG_user_female','Женский');
define('MSG_user_male','Мужской');
define('MSG_user_nogender','Предпочитаю не указывать');
define('MSG_user_icq','Номер ICQ (если есть)');
define('MSG_user_homepage','Домашняя страница или собственный сайт (если есть)');
define('MSG_user_location','Откуда');
define('MSG_user_interests','Интересы');
define('MSG_user_personalisation','Персонализация');
define('MSG_user_customtitle','Персональное звание участника');
define('MSG_user_avatar','Аватар участника');
define('MSG_user_avatartype','Тип используемого аватара');
define('MSG_user_avatarstd','Стандартный');
define('MSG_user_avatarext','Внешний');
define('MSG_user_avatarupload','Загруженный');
define('MSG_user_avselect','Выберите один из стандартных аватаров');
define('MSG_user_avpreview','Предварительный просмотр аватара');
define('MSG_user_avurl','Укажите URL внешнего аватара');
define('MSG_user_avupload','Укажите локальный путь к загружаемому аватару');
define('MSG_user_photoupload','Загрузить фотографию');
define('MSG_user_photodescr','если у вас уже загружена фотография и вы не хотите ее изменять, оставьте это поле пустым');
define('MSG_user_photodel','Удалить уже загруженную фотографию');
define('MSG_user_avatardel','Удалить уже загруженный аватар');
define('MSG_user_afterreg','После регистрации вы сможете ввести дополнительные сведения, отредактировав свой профиль');
define('MSG_user_list','Список участников форума');
define('MSG_user_profile','Профиль пользователя');
define('MSG_user_photo','Фотография');
define('MSG_user_basiclevel','Основной уровень доступа');
define('MSG_user_rating','Рейтинг пользователя');
define('MSG_user_ratepro','Повысить');
define('MSG_user_ratecontra','Понизить');
define('MSG_user_reputation','Репутация пользователя');
define('MSG_user_onforum','За время пребывания на форуме данный пользователь');
define('MSG_user_created','создал');
define('MSG_user_posted','отправил');
define('MSG_user_polled','провел');
define('MSG_user_voted','принял участие в');
define('MSG_user_regdate','Дата регистрации на форуме');
define('MSG_user_lastprofile','Последнее измение профиля');
define('MSG_user_lastvisit','Последнее посещение форума');
define('MSG_user_lastpost','Последнее сообщение');
define('MSG_user_perforum','Сообщения в разделах');
define('MSG_user_lastfvisit','Последнее посещение');
define('MSG_user_total','Всего сообщений');
define('MSG_user_connect','Связь с пользователем');
define('MSG_user_pm','Отправить личное сообщение');
define('MSG_user_sendmail','Отправить письмо по E-mail');
define('MSG_user_searchtopic','Найти все темы, созданные пользователем');
define('MSG_user_searchposts','Найти все сообщения, отправленные пользователем');
define('MSG_user_profile_activated','Ваш профиль успешно активирован!');
define('MSG_user_hidden','Не показывать ваше присутствие на форуме?');
define('MSG_user_timezonesel','Выберите ваш часовой пояс');
define('MSG_user_multilang','Показывать разделы на всех языках');
define('MSG_user_multilang_descr','Если вы выберете "нет", то будут показываться только общие разделы и разделы на языке, который выбран в качестве интерфейсного');
define('MSG_user_active','активирован');
define('MSG_user_inactive','не активирован');
define('MSG_user_timelimit','По умолчанию показывать в разделах сообщения за');
define('MSG_user_showavatars','Показывать аватары в разделах');
define('MSG_user_showavatars_descr','Вы можете отключить показ аватаров, чтобы уменьшить размер страниц форума');
define('MSG_user_claimyours','Объявить все сообщения, отправленные ранее от выбранного имени, моими');
define('MSG_user_ddoscode','Защитный код (введите цифры, которые вы видите на картинке справа)');
define('MSG_user_nocode','Включите графику, чтобы увидеть код');
define('MSG_user_aol','AIM ID');
define('MSG_user_yahoo','Yahoo Messenger');
define('MSG_user_msn','MSN');
define('MSG_user_jabber','Jabber');
define('MSG_user_diary','Онлайн дневник');
define('MSG_user_diary_comment','Если у вас есть онлайн-дневник, введите его полный URL');
define('MSG_user_extform','Использовать расширенную форму отправки сообщений');
define('MSG_user_extform_descr','Расширенная форма отправки позволяет вставлять смайлики и BoardCode в сообщения одним нажатием кнопки мыши на соответствующих картинках');
define('MSG_user_age','Возраст');
define('MSG_user_birthdate','Дата рождения');
define('MSG_user_birthdate_desc','Рекомендуется заполнить все поля, даже в том случае, если вы захотите не показывать дату или возраст. Год необходимо вводить в виде четырехзначного числа');
define('MSG_user_birthmode','Режим показа даты рождения');
define('MSG_user_bnone','Не показывать вообще');
define('MSG_user_bdate','Показывать день и месяц, скрывать возраст');
define('MSG_user_byear','Показывать возраст, скрывать дату');
define('MSG_user_ball','Показывать все');
define('MSG_user_age1','год');
define('MSG_user_age2','года');
define('MSG_user_age3','лет');
define('MSG_user_pmnotify','Отправлять уведомления на Email о новых личных сообщениях');
define('MSG_user_avatarresize','Привести размер аватара к указанному');
define('MSG_user_photoresize','Привести размер фотографии к указанному');
define('MSG_user_exisizes','Размеры внешнего аватара');
define('MSG_user_extsizesdescr','Это поле обязательно к заполнению только в том случае, если вы используете внешний аватар');
define('MSG_user_realname','Настоящее имя');
define('MSG_user_online','Сейчас на форуме');
define('MSG_user_nosigns','Показывать подписи в сообщениях');
define('MSG_user_prevmsgs','Количество предыдущих сообщений перед новым');
define('MSG_user_goto','После отправки сообщения перейти');
define('MSG_user_topicview','При заходе в тему без явного указания страницы');
define('MSG_user_topicview_start','показывать начало темы');
define('MSG_user_topicview_end','показывать последние сообщения темы');
define('MSG_user_relations','Отношения с другими пользователями');
define('MSG_user_freinds','Дружественные пользователи');
define('MSG_user_ignore','Игнорируемые');
define('MSG_user_friended','В списке дружественных у');
define('MSG_user_ignored','В списке игнорируемых у');
define('MSG_user_deleted','Пользователь удален с форума');
define('MSG_user_delete','Удаление пользователя');
define('MSG_u_selfdelete','Удалить себя с форума');
define('MSG_user_delete_info','Примачание: удаление пользователя не приводит к удалению отправленных сообщений. В дальнейшем вы сможете зарегистрироваться повторно под этим же или другим логином');

define('MSG_goto_topic','в тему с отправленным сообщением');
define('MSG_goto_forum','к списку тем в текущем разделе');
define('MSG_goto_updated','к списку обновившихся тем');
define('MSG_goto_newpost','к списку непрочитанных тем');

define('MSG_pass_restore','Восстановление забытого пароля');
define('MSG_e_u_restoreblocked','Восстановление пароля заблокировано, попробуйте позднее');
define('MSG_pass_data','Для восстановления пароля достаточно правильно указать данные хотя бы в одном из полей');
define('MSG_pass_name','Имя пользователя');
define('MSG_pass_email','Адрес Email, указанный в профиле');
define('MSG_pass_uid','Номер пользователя, полученный при регистрации');
define('MSG_pass_dosend','Выслать пароль');

define('MSG_warn','Предупреждение/поощрение пользователя');
define('MSG_warn_for','За сообщение в теме');
define('MSG_warn_alreadygot','У пользователя уже имеются следующие поощрения и предупреждения');
define('MSG_warn_none','У пользователя нет предупреждений или поощрений, активных в данный момент');
define('MSG_warn_warning','Предупреждение');
define('MSG_warn_ban','Изгнание');
define('MSG_warn_award','Поощрение');
define('MSG_warndo','Вынести');
define('MSG_warn_validtill','Срок действия');
define('MSG_warn_endless','Бессрочно');
define('MSG_warn_tilldate','До указанной даты');
define('MSG_warn_enddate','Дата окончания действия');
define('MSG_warn_from','от');
define('MSG_warn_comment','Комментарий');
define('MSG_warn_commentdescr','В комментарий не нужно включать название темы и раздела - они будут добавлены автоматически');
define('MSG_warn_from','от');
define('MSG_warn_validtill','Действительно до');
define('MSG_warn_done','Предупреждение/поощрение вынесено');

define('MSG_search','Поиск по форуму');
define('MSG_search_text','Текст для поиска');
define('MSG_search_user2','Автор сообщения');
define('MSG_search_where','Искать');
define('MSG_search_posts','сообщения и темы, содержащие данный текст');
define('MSG_search_topics','темы, в названии которых содержится данный текст');
define('MSG_search_results_out','Выводить результаты');
define('MSG_search_asposts','как сообщения');
define('MSG_search_astopic','как темы');
define('MSG_search_sortby','Сортировать по');
define('MSG_search_relevancy','релевантности');
define('MSG_search_date','дате');
define('MSG_search_reverse','в обратном порядке');
define('MSG_search_forums','Искать в разделах');
define('MSG_searchdo','Искать');
define('MSG_search_results','Результаты поиска');
define('MSG_search_got','Перейти к теме');
define('MSG_search_none','По вашему запросу ничего не было найдено');
define('MSG_search_new','Новый поиск');
define('MSG_search_goto','Перейти к теме');
define('MSG_search_starttime','Минимальная дата отправки сообщения');
define('MSG_search_endtime','Максимальная дата отправки сообщения');
define('MSG_search_noforums','Не выбран ни один раздел');
define('MSG_search_processing','Идет поиск. Пожалуйста подождите');

define('MSG_p_edit','Редактировать');
define('MSG_p_profile','Профиль');
define('MSG_p_pm','Личное сообщение');
define('MSG_p_reputation','Репутация');
define('MSG_p_delete','Удалить');
define('MSG_p_tomoder','Сообщить модератору');
define('MSG_p_title','Заголовок сообщения');
define('MSG_p_modcomment','Комментарий модератора');
define('MSG_p_attachfile','Прикрепленный файл');
define('MSG_p_post','Сообщение отправлено');
define('MSG_p_text','Текст сообщения');
define('MSG_p_html','Использование HTML');
define('MSG_p_bcode','Использование');
define('MSG_p_smiles','смайлики');
define('MSG_p_detrans','детранслитерация');
define('MSG_p_attach','Прикрепить файл');
define('MSG_p_preview','Просмотреть сообщение перед отправкой');
define('MSG_p_options','Опции отправки');
define('MSG_p_usehtml','Использовать HTML');
define('MSG_p_usebcode','Использовать BoardCode');
define('MSG_p_usesmiles','Использовать смайлики');
define('MSG_p_attachsignature','Присоединить подпись');
define('MSG_p_delete','Удалить сообщение');
define('MSG_p_close','Закрыть тему после отправки сообщения');
define('MSG_p_delattach','Удалить прикрепленный файл');
define('MSG_p_posted','написал');
define('MSG_p_sendtomoder','Сообщить модераторам о нарушении правил в теме');
define('MSG_p_complain','Текст жалобы');
define('MSG_p_complaindescr','Ссылку на тему добавлять не нужно, она будет добавлена автоматически');
define('MSG_p_done','Сообщение успешно отправлено');
define('MSG_p_create','Отправка сообщения');
define('MSG_p_edited','Сообщение успешно отредактировано');
define('MSG_p_lastedited','Сообщение отредактировано');
define('MSG_p_edit','Редактировать');
define('MSG_p_deleted','Сообщение удалено');
define('MSG_p_newmessage','Новое сообщение в теме');
define('MSG_p_quote','Цитировать');
define('MSG_p_premoderated','Сообщение успешно отправлено. Оно станет видимо после проверки модератором');
define('MSG_p_link','Ссылка');
define('MSG_p_allow','Допустить');
define('MSG_p_nochange','Оставить без изменений');
define('MSG_p_quotehelp','Для того, чтобы процитировать текст, выделите его мышкой и нажмите на ссылку. Цитирование может не работать в некоторых броузерах');
define('MSG_p_answer','Ответить');
define('MSG_p_posthide','Часть данного сообщения доступна только пользователям, отправившим не менее');
define('MSG_p_levelhide','Часть данного сообщения доступна только пользователям с более высоким уровнем');
define('MSG_p_fromname','Отправить от имени пользователя');
define('MSG_p_confirm','Вы действительно хотите удалить это сообщение');
define('MSG_p_uncut','Читать весь текст');
define('MSG_p_hidden1','Сообщение пользователя');
define('MSG_p_hidden2','скрыто');
define('MSG_p_ignore_warn1','Вы действительно хотите поместить пользователя');
define('MSG_p_ignore_warn2','в ваш личный список игнорируемых пользователей');
define('MSG_p_ignore','Игнорировать');
define('MSG_p_friend_warn1','Вы действительно хотите поместить пользователя');
define('MSG_p_friend_warn2','в список дружественных пользователей');
define('MSG_p_friend','В друзья');
define('MSG_p_onlymods','Тема только для модераторов');
define('MSG_p_downloaded','скачан');

define('MSG_subscr_select','Выбор раздела для редактирования подписки');
define('MSG_subscr_forum','Выберите раздел');
define('MSG_subscr_list','Список тем в разделе');
define('MSG_subscr_params','Параметры подписки на новые темы');
define('MSG_subscr_newtopics','Отправка уведомлений о новых темах');
define('MSG_subscr_auto','Автоматическая подписка на все новые темы');

define('MSG_v_voted','Ваш голос засчитан');

define('MSG_topic_in','эту тему');
define('MSG_f_in','этот раздел');
define('MSG_forum_in','форум');
define('MSG_in_by','за');

define('MSG_Jan','янв.');
define('MSG_Feb','фев.');
define('MSG_Mar','мар.');
define('MSG_Apr','апр.');
define('MSG_May','мая');
define('MSG_Jun','июня');
define('MSG_Jul','июля');
define('MSG_Aug','авг.');
define('MSG_Sep','сен.');
define('MSG_Oct','окт.');
define('MSG_Nov','нояб.');
define('MSG_Dec','дек.');

define('MSG_January','января');
define('MSG_February','февраля');
define('MSG_March','марта');
define('MSG_April','апреля');
define('MSG_May','мая');
define('MSG_June','июня');
define('MSG_July','июля');
define('MSG_August','августа');
define('MSG_September','сентября');
define('MSG_October','октября');
define('MSG_November','ноября');
define('MSG_December','декабря');

define('MSG_Monday','понедельник');
define('MSG_Tuesday','вторник');
define('MSG_Wednesday','среда');
define('MSG_Thursday','четверг');
define('MSG_Friday','пятница');
define('MSG_Saturday','суббота');
define('MSG_Sunday','воскресенье');

define('MSG_Mon','пн');
define('MSG_Tue','вт');
define('MSG_Wed','ср');
define('MSG_Thu','чт');
define('MSG_Fri','пт');
define('MSG_Sat','сб');
define('MSG_Sun','вс');

define('MSG_login_mode','Режим входа на форум');
define('MSG_login_normal','Обычный');
define('MSG_login_secure','Безопасный');
define('MSG_login_keep','Запомнить пользователя');

define('MSG_a_addcoment','Добавить комментарий к статье');
define('MSG_a_commentadded','Комментарий был успешно добавлен');
define('MSG_a_adding','Добавление статьи');
define('MSG_a_discussion','Обсуждение статьи');
define('MSG_a_disclink','Эта тема создана для обсуждения статьи');
define('MSG_a_added','Статья успешно добавлена');
define('MSG_a_edit','Редактирование статьи');
define('MSG_a_saved','Статья успешно сохранена');
define('MSG_a_deleteconfirm','Подтверждение удаления статьи');
define('MSG_a_editcoment','Редактирование комментария');
define('MSG_a_title','Название статьи');
define('MSG_a_author','Автор статьи');
define('MSG_a_add','Добавить статью');
define('MSG_a_origin','Первоисточник');
define('MSG_a_publisher','Статью опубликовал');
define('MSG_a_print','Версия для печати');
define('MSG_a_edit','Редактировать статью');
define('MSG_a_delete','Удалить статью');
define('MSG_a_split','Модерировать комментарии');
define('MSG_a_gotodisc','Перейти к обсуждению темы');
define('MSG_a_discusstext','Текст комментария к статье');
define('MSG_a_discussoptions','Опции комментария');
define('MSG_a_descr','Описание статьи');
define('MSG_a_authormail','E-mail автора');
define('MSG_a_amaildescr','(указывать не обязательно)');
define('MSG_a_origindescr','Внимание: если первоисточник не указан явно, то в качестве него будет указываться этот форум');
define('MSG_a_originurl','URL первоисточника');
define('MSG_a_text','Текст статьи');
define('MSG_a_discuswhere','Раздел для обсуждения статьи');
define('MSG_a_here','Обсуждать статью в этом же разделе');
define('MSG_a_lastpublish','Последнее обновление');
define('MSG_a1','статья');
define('MSG_a2','статьи');
define('MSG_a3','статей');
define('MSG_a_commentrules','При комментировании статьи не забывайте соблюдать');
define('MSG_a_ruleslink','правила раздела');
define('MSG_a_byadddate','по дате добавления');
define('MSG_a_bylastcomment','по дате последнего комментария');
define('MSG_a_bycomments','по количеству комментариев');
define('MSG_a_nobr','Не преобразовывать переводы строк в &lt;br /&gt;');
define('MSG_a_comments','Комментариев');
define('MSG_a_viewcomments','Просмотр комментариев');

define('MSG_ph_addcoment','Добавить комментарий к фотографии');
define('MSG_ph_commentadded','Комментарий был успешно добавлен');
define('MSG_ph_adding','Добавление фотографии');
define('MSG_ph_discussion','Обсуждение фотографии');
define('MSG_ph_added','Фотография успешно добавлена');
define('MSG_ph_edit','Редактирование фотографии');
define('MSG_ph_saved','Фотография успешно сохранена');
define('MSG_ph_deleteconfirm','Подтверждение удаления фотографии');
define('MSG_ph_editcoment','Редактирование комментария');
define('MSG_ph_title','Название фотографии');
define('MSG_ph_add','Добавить фото');
define('MSG_ph_publisher','Опубликовал');
define('MSG_ph_print','Версия для печати');
define('MSG_ph_edit','Редактировать фото');
define('MSG_ph_delete','Удалить фото');
define('MSG_ph_split','Модерировать комментарии');
define('MSG_ph_discusstext','Текст комментария к фотографии');
define('MSG_ph_discussoptions','Опции комментария');
define('MSG_ph_text','Текст описания фотографии');
define('MSG_ph_lastpublish','Последнее обновление');
define('MSG_ph1','фотография');
define('MSG_ph2','фотографии');
define('MSG_ph3','фотографий');
define('MSG_ph_commentrules','При комментировании фотографии не забывайте соблюдать');
define('MSG_ph_ruleslink','правила раздела');
define('MSG_ph_byadddate','по дате добавления');
define('MSG_ph_bylastcomment','по дате последнего комментария');
define('MSG_ph_bycomments','по количеству комментариев');
define('MSG_ph_comments','Комментарии');
define('MSG_ph_file','Файл с фотографией');

define('MSG_dl_title','Название файла');
define('MSG_dl_download','Скачать');
define('MSG_dl_add','Добавить файл');
define('MSG_dl_count','Количество скачиваний');
define('MSG_dl_homepage','Домашняя страница файла');
define('MSG_dl_complain','Сообщить о неработающей ссылке');
define('MSG_dl_homepagedescr','Если ссылка для скачивания не работает, попробуйте перейти на домашнюю страницу файла и скачать его оттуда');
define('MSG_dl_edit','Редактировать информацию о файле');
define('MSG_dl_delete','Удалить файл');
define('MSG_dl_split','Модерировать комментарии');
define('MSG_dl_discussion','Обсуждение файла');
define('MSG_dl_gotodisc','Перейти к обсуждению файла');
define('MSG_dl_discusstext','Текст комментария');
define('MSG_dl_discussoptions','Опции комментария');
define('MSG_dl_title','Название файла');
define('MSG_dl_shortdescr','Краткое описание');
define('MSG_dl_fulldescr','Полное описание');
define('MSG_dl_url','URL для скачивания');
define('MSG_dl_homepage','Домашняя страница файла');
define('MSG_dl_discuswhere','Раздел для обсуждения');
define('MSG_dl_here','Обсуждать статью в этом же разделе');
define('MSG_dl_lastadded','Последнее обновление');
define('MSG_dl1','файл');
define('MSG_dl2','файла');
define('MSG_dl3','файлов');
define('MSG_dl_list','Список файлов в разделе');
define('MSG_dl_addcoment','Добавить комментарий к файлу');
define('MSG_dl_check','Проверка ссылок в разделе');
define('MSG_dl_result','Результат');
define('MSG_dl_noconnect','Не удалось соединиться с сервером');
define('MSG_dl_ok','Ok');
define('MSG_dl_moved','файл перемещен');
define('MSG_dl_notfound','файл не найден');
define('MSG_dl_servererror','ошибка сервера');
define('MSG_dl_check','Проверка ссылок');
define('MSG_dl_added','Файл успешно добавлена');
define('MSG_dl_adding','Добавление файла');
define('MSG_dl_commentadded','Комментарий успешно добавлен');
define('MSG_dl_deleteconfirm','Подтверждение удаления файла');
define('MSG_dl_disclink','Эта тема создана для обсуждения файла');
define('MSG_dl_editcomment','Редактирование комментария');
define('MSG_dl_attach','Присоединить скриншот');
define('MSG_dl_screenshot','Скриншот');
define('MSG_dl_commentrules','При комментировании файла не забывайте соблюдать');
define('MSG_dl_ruleslink','правила раздела');
define('MSG_dl_byadddate','по дате добавления');
define('MSG_dl_bylastcomment','по дате последнего комментария');
define('MSG_dl_bycomments','по количеству комментариев');
define('MSG_dl_bydownloads','по количеству скачиваний');
define('MSG_dl_size','Размер файла');
define('MSG_dl_delattach','Удалить прикрепленный файл');

define('MSG_n_addcoment','Добавление комментария к новости');
define('MSG_n_commentadded','Комментарий успешно добавлен');
define('MSG_n_adding','Добавление новости');
define('MSG_n_added','Новость успешно добавлена');
define('MSG_n_edit','Редактирование новости');
define('MSG_n_editcoment','Редактирования комментария');
define('MSG_n_addedby','Новость добавил');
define('MSG_n_comment','Комментировать');
define('MSG_n_nonews','На данный момент новостей нет');
define('MSG_n_add','Добавить новость');
define('MSG_n_delete','Удалить новость');
define('MSG_n_split','Модерировать комментарии');
define('MSG_n_discussion','Обсуждение новости');
define('MSG_n_discusstext','Текст комментария');
define('MSG_n_discussoptions','Опции отправки');
define('MSG_n_title','Заголовок новости');
define('MSG_n_descr','Краткое описание новости');
define('MSG_n_text','Текст новости');
define('MSG_n_optionsdescr','Опции отправки влияют на текст новости и на ее описание');
define('MSG_n_print','Версия для печати');
define('MSG_n_delattach','Удалить картинку новости');
define('MSG_n_editcomment','Редактирование комментария');
define('MSG_n_saved','Новость успешно сохранена');
define('MSG_n_attach','Картинка для новости');
define('MSG_n_commentrules','При комментировании новости не забывайте соблюдать');
define('MSG_n_ruleslink','правила раздела');
define('MSG_n_deleteconfirm','Подтверждение удаления новости');
define('MSG_n_return_cur','Вернуться к текущим новостям');

define('MSG_n1','новость');
define('MSG_n2','новости');
define('MSG_n3','новостей');

define('MSG_comment1','комментарий');
define('MSG_comment2','комментария');
define('MSG_comment3','комментариев');

define('MSG_pr_saved','Текст статической страницы сохранен');
define('MSG_pr_lastver','Последнее обновление');
define('MSG_pr_goto_download','Перейти к скачиванию');
define('MSG_pr_download','Скачать');
define('MSG_pr_downloads','Всего скачиваний');
define('MSG_pr_edit','Редактировать текст статической страницы');
define('MSG_pr_url','URL для скачивания файла');
define('MSG_pr_url_descr','Если URL не указан, ссылка для скачивания не выводится');
define('MSG_pr_refresh','Изменить дату последнего обновления файла на текущую');
define('MSG_pr_text','Текст страницы (возможно использование HTML)');

define('MSG_en_adding','Добавление словарной статьи');
define('MSG_en_edit','Редактирование словарной статьи');
define('MSG_en_added','Словарная статья успешно добавлена');
define('MSG_en_saved','Изменения успешно сохранены');
define('MSG_en_add','Добавить словарную статью');
define('MSG_en_delete','Удалить словарную статью');
define('MSG_en_title','Название словарной статьи');
define('MSG_en_descr','Описание словарной статьи');
define('MSG_en_text','Текст словарной статьи');
define('MSG_en_tag','В тексте можно использовать тег [word] для простановки ссылок на другие словарные статьи. Например, [word]слово[/word] будет заменено ссылкой на словарную статью "слово", если такая существует');
define('MSG_en_attach','Прикрепленный файл');
define('MSG_en_lastpublish','Последнее обновление');
define('MSG_en_deleteconfirm','Вы действительно хотите удалить словарную статью');
define('MSG_e_en_emptytitle','Ошибка! Не введено название словарной статьи');
define('MSG_e_en_emptytext','Ошибка! Не введен текст словарной статьи');
define('MSG_en1','статья');
define('MSG_en2','статьи');
define('MSG_en3','статей');

define('MSG_resend','Повторная высылка письма для активации');
define('MSG_resend_done','Письмо с кодом активации было выслано на новый Email');
define('MSG_resend_text','Если письмо с кодом активации не дошло на указанный вами адрес, вы можете попробовать указать другой адрес Email');
define('MSG_resend_name','Имя пользователя, под которым вы регистрировались');
define('MSG_resend_pass','Пароль, указанный при регистрации');
define('MSG_resend_newmail','Новый адрес Email');

define('MSG_allow_post','отправлять сообщения');
define('MSG_allow_topic','создавать темы');
define('MSG_allow_vote','голосовать в опросах');
define('MSG_allow_poll','создавать опросы');
define('MSG_allow_edit','редактировать свои сообщения');
define('MSG_allow_attach','прикреплять к сообщениям файлы');
define('MSG_allow_moderate','модерировать раздел');
define('MSG_allow_ip','видеть IP-адреса');

define('MSG_us_nodata','Не указаны данные для поиска');
define('MSG_us_extsearch','Расширенный поиск пользователей');
define('MSG_us_mode','Режим поиска по имени');
define('MSG_us_exact','Точное совпадение');
define('MSG_us_begins','Начинается с');
define('MSG_us_contains','Содержит');
define('MSG_us_email','Только пользователи с видимым адресом Email');
define('MSG_us_ICQ','Только пользователи с ICQ');
define('MSG_us_photo','Только пользователи с фотографией');
define('MSG_us_minlevel','Пользователи с уровнем не ниже');
define('MSG_us_search','Начать поиск');
define('MSG_us_result','Результаты расширенного поиска пользователей');

define('MSG_send','Отправить');
define('MSG_add','Добавить');
define('MSG_register','Зарегистрироваться');
define('MSG_forgot_password','Забыли');
define('MSG_save','Сохранить');
define('MSG_save_continue','Сохранить и продолжить редактирование');
define('MSG_send_continue','Данные отосланы на сервер. Вы можете продолжать редактирование');
define('MSG_bcode','Использовать BoardCode');
define('MSG_smiles','Использовать смайлики');
define('MSG_attachsign','Присоединить подпись');
define('MSG_delete','Удалить');
define('MSG_no','Нет');
define('MSG_yes','Да');
define('MSG_author','Автор');
define('MSG_move','Переместить');
define('MSG_copy','Копировать');
define('MSG_sticky','Приклееная тема');
define('MSG_stickypost','Приклееное сообщение');
define('MSG_inrating','Участвует в рейтинге');
define('MSG_preview','Просмотреть');
define('MSG_login','Вход на форум');
define('MSG_dologin','Войти');
define('MSG_name','Имя');
define('MSG_title','Звание');
define('MSG_level','Уровень');
define('MSG_p_count','Сообщений');
define('MSG_gender','Пол');
define('MSG_location','Откуда');
define('MSG_email','E-mail');
define('MSG_homepage','Сайт');
define('MSG_regdate','Дата регистрации');
define('MSG_lastvisit','Последний визит в раздел');
define('MSG_have','Есть');
define('MSG_intopic','в теме');
define('MSG_inforum','раздела');
define('MSG_present','Пользователи, присутствующие на форуме');
define('MSG_lastvisit','Последний раз вы посетили раздел');
define('MSG_welcome','Добро пожаловать в раздел');
define('MSG_asc','возрастанию');
define('MSG_desc','убыванию');
define('MSG_show','Вывести');
define('MSG_hide','Скрыть');
define('MSG_showby','вывести по');
define('MSG_show_last','Выводить темы за');
define('MSG_newtopic','Новая тема');
define('MSG_newpoll','Новый опрос');
define('MSG_moderator','Модератор');
define('MSG_moderators','Модераторы');
define('MSG_forbidden','запрещено');
define('MSG_allowed','разрешено');
define('MSG_usage','Использовать');
define('MSG_automatic','Автоматическая');
define('MSG_enabled','включена');
define('MSG_disabled','выключена');
define('MSG_post','Отправить');
define('MSG_addvariants','Добавить варианты');
define('MSG_prevpage','Вернуться на предыдущую страницу');
define('MSG_none','Нет');
define('MSG_edit','Редактировать');
define('MSG_groups','Группы участников');
define('MSG_offorum','раздела');
define('MSG_topic','Тема');
define('MSG_announce','Объявление форума');
define('MSG_admincenter','Перейти в Центр Администрирования');
define('MSG_newposts','Темы, содержащие непрочитанные сообщения');
define('MSG_markall','Отметить все сообщения как прочитанные');
define('MSG_nonewposts','С вашего последнего визита на форуме новых сообщений не появилось');
define('MSG_shownewposts','Новые сообщения');
define('MSG_written','написал');
define('MSG_clear','Очистить');
define('MSG_warnlist','Список предупреждений/поощрений');
define('MSG_prev','Назад');
define('MSG_next','Вперед');
define('MSG_offtopic','Оффтопик');
define('MSG_unselect','Снять выделение');
define('MSG_select','Выбрать все');
define('MSG_userlogin','Логин');
define('MSG_password','Пароль');
define('MSG_extlink','Внешняя ссылка');
define('MSG_extlinkclick','Данный раздел является внешней ссылкой. Если ваш броузер не перешел автоматически, щелкните мышью по ссылке ниже');
define('MSG_or','или');
define('MSG_photo','Фото');
define('MSG_bytes','байт');
define('MSG_selectall','Выделить все');
define('MSG_unselectall','Снять выделение');
define('MSG_cant','Вы не можете');
define('MSG_can','Вы можете');
define('MSG_image','Изображение');
define('MSG_off','Выключено');
define('MSG_on','Включено');

define('MSG_fl_per','файлов на страницу');
define('MSG_fl_sortby','Сортировать по');
define('MSG_fl_bypostdate','дате отправки сообщения');
define('MSG_fl_bypostedit','дате последнего редактирования');
define('MSG_fl_bytopic','теме');
define('MSG_fl_byforum','разделу');
define('MSG_fl_byname','названию файла');
define('MSG_fl_bysize','размеру файла');
define('MSG_fl_bytype','типу файла');
define('MSG_fl_name','Имя файла');
define('MSG_fl_post','Текст сообщения');
define('MSG_fl_topic','Тема');
define('MSG_fl_forum','Раздел');
define('MSG_fl_size','Размер');
define('MSG_fl_type','Тип');
define('MSG_fl_lastmod','Дата');
define('MSG_fl_noentries','Ни одного прикрепленного файла не обнаружено');
define('MSG_fl_filelist','Список прикрепленных файлов');
define('MSG_fl_files','Файлы');

define('MSG_todraft','Сохранить в черновик');
define('MSG_ctrlenter','Для быстрой отправки сообщения можно использовать Ctrl+Enter, когда курсор находится в поле ввода текста');
define('MSG_draft_save','Промежуточное сохранение сообщения (Alt+D). Чтобы потом продолжить его редактирование, выберите пункт меню &quot;Черновики&quot; и нажмите &quot;Продолжить редактирование&quot;');
define('MSG_draft_senddel','Удалить черновик после отправки сообщения');
define('MSG_dr_sent','Сообщение было сохранено в черновик. Теперь вы можете продолжать его редактирование. Обратите внимание: прикрепленные файлы не сохраняются!');
define('MSG_dr_text','Текст сообщения');
define('MSG_dr_topic','Тема');
define('MSG_dr_forum','Раздел');
define('MSG_dr_continue','Продолжить редактирование');
define('MSG_dr_noentries','У вас нет черновиков');
define('MSG_dr_draftlist','Список черновиков');
define('MSG_dr_deleted','Выбранные черновики удалены');
define('MSG_dr_noselected','Ни один черновик не выбран');
define('MSG_dr_drafts','Черновики');
define('MSG_dr_old','Удалить сообщение из черновика при отправке');

define('MSG_blog_addcoment','Добавление комментария к сообщению');
define('MSG_blog_commentadded','Комментарий успешно добавлен');
define('MSG_blog_adding','Добавление записи в блог');
define('MSG_blog_added','Запись успешно добавлена в блог');
define('MSG_blog_edit','Редактирование записи блога');
define('MSG_blog_editcoment','Редактирование комментария');
define('MSG_blog_comment','Добавить комментарий');
define('MSG_blog_nonews','В этом блоге еще нет записей');
define('MSG_blog_add','Добавить запись');
define('MSG_blog_delete','Удалить запись');
define('MSG_blog_split','Модерировать комментарии');
define('MSG_blog_discusstext','Текст комментария');
define('MSG_blog_discussoptions','Опции отправки');
define('MSG_blog_title','Название записи');
define('MSG_blog_text','Текст записи');
define('MSG_blog_print','Версия для печати');
define('MSG_blog_delattach','Удалить прикрепленный файл');
define('MSG_blog_editcomment','Редактирование комментария');
define('MSG_blog_saved','Запись блога успешно сохранена');
define('MSG_blog_attach','Картинка для записи');
define('MSG_blog_commentrules','При комментировании новости не забывайте соблюдать');
define('MSG_blog_ruleslink','правила раздела');
define('MSG_blog_deleteconfirm','Подтверждение удаления записи блога');
define('MSG_blog_return_cur','Вернуться к текущим записям');
define('MSG_blog_maintitle','Название блога');
define('MSG_blog_descr','Описание блога');
define('MSG_blog_lview','Уровень пользователей, которым разрешен просмотр блога');
define('MSG_blog_lread','Уровень пользователей, котором разрешено чтение блога');
define('MSG_blog_lpost','Уровень пользователей, которым разрешены комментарии');
define('MSG_blog_lpremod','Уровень пользователей, чьи комментарии не будут ставиться на премодерацию');
define('MSG_blog_discussion','Комментарии к записи блога');
define('MSG_blog_owner','Владелец блога');

define('MSG_gallery_maintitle','Название личной галереи');
define('MSG_gallery_descr','Описание личной галереи');
define('MSG_gallery_lview','Уровень пользователей, которым разрешен просмотр галереи');
define('MSG_gallery_lread','Уровень пользователей, котором разрешен просмотр фотографий');
define('MSG_gallery_lpost','Уровень пользователей, которым разрешены комментарии');
define('MSG_gallery_lpremod','Уровень пользователей, чьи комментарии не будут ставиться на премодерацию');
define('MSG_gallery_owner','Владелец галереи');

define('MSG_ab_ignored','Пользователь добавлен в список игнорируемых');
define('MSG_ab_list','Список дружественных и игнорируемых пользователей');
define('MSG_ab_saved','Списки пользователей сохранены');
define('MSG_ab_friends','Список дружественных пользователей');
define('MSG_ab_nofriends','Дружественных пользователей нет');
define('MSG_ab_enemies','Список игнорируемых');
define('MSG_ab_noenemies','Игнорируемых пользователей нет');
define('MSG_ab_addfriends','Добавить в список дружественных пользователей');
define('MSG_ab_addenemies','Добавить в список игнорируемых пользователей');
define('MSG_ab_save','Сохранить изменения');
define('MSG_ab_hint1','Отметьте галочками в списке тех пользователей, которых вы хотите удалить');
define('MSG_ab_hint2','Добавлять в списки можно нескольких пользователей одновременно, если ввести их имена через запятую');
define('MSG_ab_friended','Пользователь добавлен в список дружественных');
define('MSG_ab_choose_friend','Выберите получателя пользователя из списка');

define('MSG_ignore_forums','Игнорировать разделы в списке "Обновившихся" и "Непрочитанных"');
define('MSG_ignore_saved','Список игнорируемых разделов сохранен');
define('MSG_ignore_loc','Игнорируемые разделы');

define('MSG_disp_comments','Показать комментарии');
define('MSG_disp_comments_to','Комментарии к');
define('MSG_disp_comment1','комментарий');
define('MSG_disp_comment2','комментария');
define('MSG_disp_comment3','комментариев');

define('MSG_rss_saved','Список импорта RSS сохранен');
define('MSG_rss_url','URL RSS для импорта');
define('MSG_rss_name','Название RSS-ленты');
define('MSG_rss_source','Текст, который будет писаться в качестве первоистичника');
define('MSG_rss_premoderate','Ставить на премодерацию');
define('MSG_rss_list','Список импортируемых RSS');
define('MSG_rss_import','Импорт RSS');

define('MSG_fdl1','раз');
define('MSG_fdl2','раза');
define('MSG_fdl3','раз');

define('MSG_search_small','Поиск');
define('MSG_hi','Добро пожаловать');
define('MSG_p_post_gram','Отправлено');
define('MSG_p_lastedited_gram','Исправлено');
define('MSG_quote', 'Цитата');
define('MSG_first_msg', 'Первое сообщение темы');
define('MSG_t_subscribe_n','Присылать уведомления об ответе');

define('MSG_views1','просмотр');
define('MSG_views2','просмотра');
define('MSG_views3','просмотров');
?>